-- ROCK9086: after 002_apply.sql, confirm the old text is gone and the new text is present.
SET NOCOUNT ON;
SELECT 'AttributeValue' Tbl, 113183797 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue:''\d+''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue:''[0-9]+''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 113183797; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 2211072 Id, 'and-or' FixRule, CHARINDEX(N'{% if Location.FormattedHtmlAddress && Location.FormattedHtmlAddress != '''' %}', [Value]) StillHasOld, CHARINDEX(N'{% if Location.FormattedHtmlAddress and Location.FormattedHtmlAddress != '''' %}', [Value]) HasNew FROM AttributeValue WHERE [Id] = 2211072; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 2236004 Id, 'and-or' FixRule, CHARINDEX(N'{% if Location.FormattedHtmlAddress && Location.FormattedHtmlAddress != '''' %}', [Value]) StillHasOld, CHARINDEX(N'{% if Location.FormattedHtmlAddress and Location.FormattedHtmlAddress != '''' %}', [Value]) HasNew FROM AttributeValue WHERE [Id] = 2236004; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 2518517 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatch:''\d\d-\d\d-\d\d\d\d''', [Value]) StillHasOld, CHARINDEX(N'RegExMatch:''[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 2518517; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 309623673 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 309623673; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 309623682 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 309623682; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 365403708 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 365403708; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 365407926 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 365407926; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 365407929 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 365407929; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 365407957 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 365407957; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 365407965 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 365407965; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 365408103 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 365408103; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 365408106 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 365408106; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 365408134 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 365408134; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 365408142 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [Value]) StillHasOld, CHARINDEX(N'sixMthsAgo', [Value]) HasNew FROM AttributeValue WHERE [Id] = 365408142; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 368569934 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue:''\d+''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue:''[0-9]+''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 368569934; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 386443565 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue:''\d+''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue:''[0-9]+''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 386443565; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 4199436 Id, 'and-or' FixRule, CHARINDEX(N'{% if StreetAddress2 != null && StreetAddress2 != '''' %}', [Value]) StillHasOld, CHARINDEX(N'{% if StreetAddress2 != null and StreetAddress2 != '''' %}', [Value]) HasNew FROM AttributeValue WHERE [Id] = 4199436; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 4199439 Id, 'and-or' FixRule, CHARINDEX(N'{% if StreetAddress2 != null && StreetAddress2 != '''' %}', [Value]) StillHasOld, CHARINDEX(N'{% if StreetAddress2 != null and StreetAddress2 != '''' %}', [Value]) HasNew FROM AttributeValue WHERE [Id] = 4199439; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 4199441 Id, 'and-or' FixRule, CHARINDEX(N'{% if StreetAddress2 != null && StreetAddress2 != '''' %}', [Value]) StillHasOld, CHARINDEX(N'{% if StreetAddress2 != null and StreetAddress2 != '''' %}', [Value]) HasNew FROM AttributeValue WHERE [Id] = 4199441; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 46829156 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue:''([Pp][Rr][Aa][Yy]4)([Bb][Bb]|[Mm][Ii][Xx]|[Ss][Ee]!?[Kk][Ii][Dd][Ss]|[Cc][Aa][Mm][Pp][Ff][Rr][Ee][Ee][Dd][Oo][Mm])(920|[Cc][Ww]|[Ll][Aa]|[Ss][Ww]|[Ii][Nn]|[Ee][Tt]|[Rr][Vv]|[\d])?''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue:''([Pp][Rr][Aa][Yy]4)([Bb][Bb]|[Mm][Ii][Xx]|[Ss][Ee]!?[Kk][Ii][Dd][Ss]|[Cc][Aa][Mm][Pp][Ff][Rr][Ee][Ee][Dd][Oo][Mm])(920|[Cc][Ww]|[Ll][Aa]|[Ss][Ww]|[Ii][Nn]|[Ee][Tt]|[Rr][Vv]|[0-9])?''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 46829156; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 46829261 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue:''([Pp][Rr][Aa][Yy]4)([Bb][Bb]|[Mm][Ii][Xx]|[Ss][Ee]!?[Kk][Ii][Dd][Ss]|[Cc][Aa][Mm][Pp][Ff][Rr][Ee][Ee][Dd][Oo][Mm])(920|[Cc][Ww]|[Ll][Aa]|[Ss][Ww]|[Ii][Nn]|[Ee][Tt]|[Rr][Vv]|[\d])?''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue:''([Pp][Rr][Aa][Yy]4)([Bb][Bb]|[Mm][Ii][Xx]|[Ss][Ee]!?[Kk][Ii][Dd][Ss]|[Cc][Aa][Mm][Pp][Ff][Rr][Ee][Ee][Dd][Oo][Mm])(920|[Cc][Ww]|[Ll][Aa]|[Ss][Ww]|[Ii][Nn]|[Ee][Tt]|[Rr][Vv]|[0-9])?''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 46829261; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 46829467 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue:''([Pp][Rr][Aa][Yy]4)([Bb][Bb]|[Mm][Ii][Xx]|[Ss][Ee]!?[Kk][Ii][Dd][Ss]|[Cc][Aa][Mm][Pp][Ff][Rr][Ee][Ee][Dd][Oo][Mm])(920|[Cc][Ww]|[Ll][Aa]|[Ss][Ww]|[Ii][Nn]|[Ee][Tt]|[Rr][Vv]|[\d])?''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue:''([Pp][Rr][Aa][Yy]4)([Bb][Bb]|[Mm][Ii][Xx]|[Ss][Ee]!?[Kk][Ii][Dd][Ss]|[Cc][Aa][Mm][Pp][Ff][Rr][Ee][Ee][Dd][Oo][Mm])(920|[Cc][Ww]|[Ll][Aa]|[Ss][Ww]|[Ii][Nn]|[Ee][Tt]|[Rr][Vv]|[0-9])?''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 46829467; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 50572183 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatch:''(Campus)=+(\w+)''', [Value]) StillHasOld, CHARINDEX(N'RegExMatch:''(Campus)=+([A-Za-z0-9_]+)''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 50572183; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 50572183 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue:''(Campus)=+(\w+)''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue:''(Campus)=+([A-Za-z0-9_]+)''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 50572183; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 56820527 Id, 'and-or' FixRule, CHARINDEX(N'{% if Location.FormattedHtmlAddress && Location.FormattedHtmlAddress != '''' %}', [Value]) StillHasOld, CHARINDEX(N'{% if Location.FormattedHtmlAddress and Location.FormattedHtmlAddress != '''' %}', [Value]) HasNew FROM AttributeValue WHERE [Id] = 56820527; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 60895356 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue:''\d+''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue:''[0-9]+''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 60895356; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 62012675 Id, 'and-or' FixRule, CHARINDEX(N'{% if eventItemOccurrence.CustomDateText != null && eventItemOccurrence.CustomDateText != '''' -%}', [Value]) StillHasOld, CHARINDEX(N'{% if eventItemOccurrence.CustomDateText != null and eventItemOccurrence.CustomDateText != '''' -%}', [Value]) HasNew FROM AttributeValue WHERE [Id] = 62012675; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 62012675 Id, 'and-or' FixRule, CHARINDEX(N'{% if eventItemOccurrence.CustomLocationText != null && eventItemOccurrence.CustomLocationText != '''' -%}', [Value]) StillHasOld, CHARINDEX(N'{% if eventItemOccurrence.CustomLocationText != null and eventItemOccurrence.CustomLocationText != '''' -%}', [Value]) HasNew FROM AttributeValue WHERE [Id] = 62012675; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 71173937 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue: ''\d+''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue: ''[0-9]+''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 71173937; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 75394059 Id, 'sort-two-arg' FixRule, CHARINDEX(N'| Sort:''StartDateTime'', ''desc''', [Value]) StillHasOld, CHARINDEX(N'| OrderBy:''StartDateTime desc''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 75394059; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 75416089 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue:''\d+''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue:''[0-9]+''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 75416089; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 76017355 Id, 'regex-escape' FixRule, CHARINDEX(N'RegExMatchValue:''\d+''', [Value]) StillHasOld, CHARINDEX(N'RegExMatchValue:''[0-9]+''', [Value]) HasNew FROM AttributeValue WHERE [Id] = 76017355; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 77081653 Id, 'and-or' FixRule, CHARINDEX(N'{% if person.FirstName == firstName && person.LastName == lastName -%}', [Value]) StillHasOld, CHARINDEX(N'{% if person.FirstName == firstName and person.LastName == lastName -%}', [Value]) HasNew FROM AttributeValue WHERE [Id] = 77081653; -- expect 0, >0
SELECT 'AttributeValue' Tbl, 79262765 Id, 'and-or+manual-latlng' FixRule, CHARINDEX(N'{% if lng != '''' && lng != '''' -%}', [Value]) StillHasOld, CHARINDEX(N'{% if lat != '''' and lng != '''' -%}', [Value]) HasNew FROM AttributeValue WHERE [Id] = 79262765; -- expect 0, >0
SELECT 'Attribute' Tbl, 12442 Id, 'and-or' FixRule, CHARINDEX(N'{% if Location.FormattedHtmlAddress && Location.FormattedHtmlAddress != '''' %}', [DefaultValue]) StillHasOld, CHARINDEX(N'{% if Location.FormattedHtmlAddress and Location.FormattedHtmlAddress != '''' %}', [DefaultValue]) HasNew FROM Attribute WHERE [Id] = 12442; -- expect 0, >0
SELECT 'HtmlContent' Tbl, 1290 Id, 'sort-empty-arg' FixRule, CHARINDEX(N'| Sort:''''', [Content]) StillHasOld, CHARINDEX(N'| Sort', [Content]) HasNew FROM HtmlContent WHERE [Id] = 1290 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 3535); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 1594 Id, 'sort-empty-arg' FixRule, CHARINDEX(N'| Sort:''''', [Content]) StillHasOld, CHARINDEX(N'| Sort', [Content]) HasNew FROM HtmlContent WHERE [Id] = 1594 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 3897); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 1661 Id, 'sort-two-arg' FixRule, CHARINDEX(N'| Sort:''Order'',''Asc''', [Content]) StillHasOld, CHARINDEX(N'| OrderBy:''Order''', [Content]) HasNew FROM HtmlContent WHERE [Id] = 1661 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 3973); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 2379 Id, 'and-or' FixRule, CHARINDEX(N'{% if Context.Person.GivingId != empty && Context.Person.GivingId != '''' %}', [Content]) StillHasOld, CHARINDEX(N'{% if Context.Person.GivingId != empty and Context.Person.GivingId != '''' %}', [Content]) HasNew FROM HtmlContent WHERE [Id] = 2379 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 4730); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 2397 Id, 'and-or' FixRule, CHARINDEX(N'{% if Context.Person.GivingId != empty && Context.Person.GivingId != '''' %}', [Content]) StillHasOld, CHARINDEX(N'{% if Context.Person.GivingId != empty and Context.Person.GivingId != '''' %}', [Content]) HasNew FROM HtmlContent WHERE [Id] = 2397 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 4744); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 3386 Id, 'sort-two-arg' FixRule, CHARINDEX(N'| Sort:''Order'',''Asc''', [Content]) StillHasOld, CHARINDEX(N'| OrderBy:''Order''', [Content]) HasNew FROM HtmlContent WHERE [Id] = 3386 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 5114); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 3641 Id, 'and-or' FixRule, CHARINDEX(N'{% if registrationId != null && registrationId != '''' && registrationId != 0 %}', [Content]) StillHasOld, CHARINDEX(N'{% if registrationId != null and registrationId != '''' and registrationId != 0 %}', [Content]) HasNew FROM HtmlContent WHERE [Id] = 3641 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 5235); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 4088 Id, 'nested-comment' FixRule, (LEN([Content]) - LEN(REPLACE([Content], N'{% comment %}', N''))) / LEN(N'{% comment %}') CommentTags, (LEN([Content]) - LEN(REPLACE([Content], N'{% endcomment %}', N''))) / LEN(N'{% endcomment %}') EndCommentTags FROM HtmlContent WHERE [Id] = 4088 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 5362); -- expect 1, 1
SELECT 'LavaShortcode' Tbl, 11 Id, 'else-trim' FixRule, CHARINDEX(N'{% else- %}', [Markup]) StillHasOld, CHARINDEX(N'{% else -%}', [Markup]) HasNew FROM LavaShortcode WHERE [Id] = 11; -- expect 0, >0
SELECT 'HtmlContent' Tbl, 4100 Id, 'sort-two-arg' FixRule, CHARINDEX(N'| Sort:''Order'',''Asc''', [Content]) StillHasOld, CHARINDEX(N'| OrderBy:''Order''', [Content]) HasNew FROM HtmlContent WHERE [Id] = 4100 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 5373); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 4109 Id, 'sort-two-arg' FixRule, CHARINDEX(N'| Sort:''Order'',''Asc''', [Content]) StillHasOld, CHARINDEX(N'| OrderBy:''Order''', [Content]) HasNew FROM HtmlContent WHERE [Id] = 4109 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 5382); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 4169 Id, 'sort-two-arg' FixRule, CHARINDEX(N'| Sort:''Order'',''Asc''', [Content]) StillHasOld, CHARINDEX(N'| OrderBy:''Order''', [Content]) HasNew FROM HtmlContent WHERE [Id] = 4169 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 5386); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 4170 Id, 'and-or' FixRule, CHARINDEX(N'{% if person != null && person != empty %}', [Content]) StillHasOld, CHARINDEX(N'{% if person != null and person != empty %}', [Content]) HasNew FROM HtmlContent WHERE [Id] = 4170 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 5391); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 4183 Id, 'sort-empty-arg' FixRule, CHARINDEX(N'| Sort:''''', [Content]) StillHasOld, CHARINDEX(N'| Sort', [Content]) HasNew FROM HtmlContent WHERE [Id] = 4183 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 5395); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 4261 Id, 'sort-two-arg' FixRule, CHARINDEX(N'| Sort:''Order'',''Asc''', [Content]) StillHasOld, CHARINDEX(N'| OrderBy:''Order''', [Content]) HasNew FROM HtmlContent WHERE [Id] = 4261 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 5576); -- expect 0, >0
SELECT 'HtmlContent' Tbl, 6548 Id, 'sort-two-arg' FixRule, CHARINDEX(N'| Sort:''Order'',''Asc''', [Content]) StillHasOld, CHARINDEX(N'| OrderBy:''Order''', [Content]) HasNew FROM HtmlContent WHERE [Id] = 6548 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent WHERE BlockId = 6438); -- expect 0, >0
SELECT 'WorkflowActionFormAttribute' Tbl, 20849 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [PostHtml]) StillHasOld, CHARINDEX(N'sixMthsAgo', [PostHtml]) HasNew FROM WorkflowActionFormAttribute WHERE [Id] = 20849; -- expect 0, >0
SELECT 'WorkflowActionFormAttribute' Tbl, 20960 Id, 'numeric-variable' FixRule, CHARINDEX(N'6MthsAgo', [PostHtml]) StillHasOld, CHARINDEX(N'sixMthsAgo', [PostHtml]) HasNew FROM WorkflowActionFormAttribute WHERE [Id] = 20960; -- expect 0, >0
SELECT 'WorkflowActionForm' Tbl, 456 Id, 'and-or' FixRule, CHARINDEX(N'{% if child.Age < 6 && grade == '''' %}', [Header]) StillHasOld, CHARINDEX(N'{% if child.Age < 6 and grade == '''' %}', [Header]) HasNew FROM WorkflowActionForm WHERE [Id] = 456; -- expect 0, >0
SELECT 'WorkflowActionForm' Tbl, 531 Id, 'and-or' FixRule, CHARINDEX(N'{% if attribute.IsRequired && attribute.Value == Empty %}', [Header]) StillHasOld, CHARINDEX(N'{% if attribute.IsRequired and attribute.Value == Empty %}', [Header]) HasNew FROM WorkflowActionForm WHERE [Id] = 531; -- expect 0, >0
