-- ROCK9086 pass 7: rows production reported under Fluid verification on 2026-09-25 after 009 (14:45-16:05).
-- Generated by gen_010.py from the live prod values; every REPLACE was checked against them before writing this file.
-- Same shape as 005-009: guarded REPLACE per row, @DryRun = 1 rolls back, live run is all-or-nothing, backups to
-- dbo._ROCK9086_LavaBackup, rows absent from the target database log -1. Clear the Rock cache afterwards.
--
-- Rows                                           Pattern                                            Fluid today / fix
-- ReportField x25 (family "Children:/Parents:"    {% if forloop.rindex > 1 %},{% endif %}               Fluid 2.3.1 numbers rindex backwards: the comma
--   Lava fields in 25 staff/family reports)                                                          lands on the wrong items -> forloop.last == false
-- HtmlContent 12894 (block 6700, /links/{slug})  hideTitle == false, roundHeaderImage == true       RawValue is the string 'True'/'False'; Fluid
--                                                 against Attribute ... 'RawValue'                   never matches -> heading hidden; compare strings
-- WorkflowType 47, 724, 732, 733, 734             {% assign completed = false %} ... == 'false'       bool vs string: Fluid matches neither branch ->
--   NoActionMessage (volunteer / church reference)                                                   message blank; {% if completed %} / {% else %}
-- AttributeValue x5 (workflow 639 email bodies)   {% assign X = {{Workflow | Attribute:...}} %}      "A value was expected" -> bare expression
-- AttributeValue 145692343, 328460478, 340611135  "Name": "{{g.Name}}" etc. unescaped in JSON       a group name with a " breaks webrequest on
--   (publishgroup/list, /v2, /aigroupfinder)                                                         Fluid -> Replace:'"',bsq (same fix as 006)
-- AttributeValue 449094742 (RSVP Weekend (FINAL)) RegExMatch:'^([0-9])\1\1...'                      \1 escape in a quoted string -> capture
-- Every rewrite verified identical on both engines with LavaProbe (F1, F2, H*, G1-G4, J4, F7).
SET NOCOUNT ON; SET XACT_ABORT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
DECLARE @DryRun bit = 1;
DECLARE @log TABLE (Tbl sysname, Id int, FixRule varchar(40), [Rows] int);
BEGIN TRAN;

IF OBJECT_ID('dbo._ROCK9086_LavaBackup') IS NULL
    CREATE TABLE dbo._ROCK9086_LavaBackup (Tbl sysname NOT NULL, Id int NOT NULL, Col sysname NOT NULL, OldValue nvarchar(max) NULL, BackedUpAt datetime NOT NULL DEFAULT GETDATE());

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'ReportField', x.[Id], 'Selection', x.[Selection] FROM ReportField x WHERE x.[Id] IN (12971, 13584, 16741, 31643, 31741, 31781, 51017, 53633, 53685, 53699, 64216, 64230, 64999, 66158, 66604, 69381, 69400, 69427, 69847, 70125, 70138, 70216, 70226, 70394, 70469)
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'ReportField' AND b.Id = x.[Id]);
INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'HtmlContent', x.[Id], 'Content', x.[Content] FROM HtmlContent x WHERE x.[Id] IN (12894)
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'HtmlContent' AND b.Id = x.[Id]);
INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'WorkflowType', x.[Id], 'NoActionMessage', x.[NoActionMessage] FROM WorkflowType x WHERE x.[Id] IN (47, 724, 732, 733, 734)
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'WorkflowType' AND b.Id = x.[Id]);
INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM AttributeValue x WHERE x.[Id] IN (119518134, 119518144, 165745851, 175793856, 181933899, 145692343, 328460478, 340611135, 449094742)
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id]);

UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 12971
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 12971, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 13584
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 13584, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 16741
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 16741, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 31643
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 31643, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 31741
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 31741, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 31781
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 31781, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 51017
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 51017, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 53633
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 53633, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 53685
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 53685, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 53699
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 53699, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 64216
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 64216, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 64230
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 64230, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 64999
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 64999, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 66158
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 66158, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 66604
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 66604, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 69381
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 69381, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 69400
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 69400, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 69427
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 69427, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 69847
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 69847, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 70125
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 70125, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 70138
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 70138, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 70216
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 70216, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 70226
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 70226, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 70394
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 70394, 'rindex-comma', @@ROWCOUNT);
UPDATE ReportField SET [Selection] = REPLACE([Selection], N'forloop.rindex > 1', N'forloop.last == false')
WHERE [Id] = 70469
  AND (LEN([Selection]) - LEN(REPLACE([Selection], N'forloop.rindex > 1', N''))) / LEN(N'forloop.rindex > 1') = 1;
INSERT @log VALUES ('ReportField', 70469, 'rindex-comma', @@ROWCOUNT);
UPDATE HtmlContent SET [Content] = REPLACE(REPLACE([Content], N'{%- if hideTitle == false -%}', N'{%- if hideTitle == ''False'' -%}'), N'{% if roundHeaderImage == true %}', N'{% if roundHeaderImage == ''True'' %}')
WHERE [Id] = 12894
  AND (LEN([Content]) - LEN(REPLACE([Content], N'{%- if hideTitle == false -%}', N''))) / LEN(N'{%- if hideTitle == false -%}') = 1
  AND (LEN([Content]) - LEN(REPLACE([Content], N'{% if roundHeaderImage == true %}', N''))) / LEN(N'{% if roundHeaderImage == true %}') = 1 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = 6700);
INSERT @log VALUES ('HtmlContent', 12894, 'bool-vs-rawvalue', @@ROWCOUNT);
UPDATE WorkflowType SET [NoActionMessage] = REPLACE(REPLACE([NoActionMessage], N'{% if completed == ''true'' %}', N'{% if completed %}'), N'{% elseif completed == ''false'' %}', N'{% else %}')
WHERE [Id] = 47
  AND (LEN([NoActionMessage]) - LEN(REPLACE([NoActionMessage], N'{% if completed == ''true'' %}', N''))) / LEN(N'{% if completed == ''true'' %}') = 1
  AND (LEN([NoActionMessage]) - LEN(REPLACE([NoActionMessage], N'{% elseif completed == ''false'' %}', N''))) / LEN(N'{% elseif completed == ''false'' %}') = 1;
INSERT @log VALUES ('WorkflowType', 47, 'bool-vs-string', @@ROWCOUNT);
UPDATE WorkflowType SET [NoActionMessage] = REPLACE(REPLACE([NoActionMessage], N'{% if completed == ''true'' %}', N'{% if completed %}'), N'{% elseif completed == ''false'' %}', N'{% else %}')
WHERE [Id] = 724
  AND (LEN([NoActionMessage]) - LEN(REPLACE([NoActionMessage], N'{% if completed == ''true'' %}', N''))) / LEN(N'{% if completed == ''true'' %}') = 1
  AND (LEN([NoActionMessage]) - LEN(REPLACE([NoActionMessage], N'{% elseif completed == ''false'' %}', N''))) / LEN(N'{% elseif completed == ''false'' %}') = 1;
INSERT @log VALUES ('WorkflowType', 724, 'bool-vs-string', @@ROWCOUNT);
UPDATE WorkflowType SET [NoActionMessage] = REPLACE(REPLACE([NoActionMessage], N'{% if completed == ''true'' %}', N'{% if completed %}'), N'{% elseif completed == ''false'' %}', N'{% else %}')
WHERE [Id] = 732
  AND (LEN([NoActionMessage]) - LEN(REPLACE([NoActionMessage], N'{% if completed == ''true'' %}', N''))) / LEN(N'{% if completed == ''true'' %}') = 1
  AND (LEN([NoActionMessage]) - LEN(REPLACE([NoActionMessage], N'{% elseif completed == ''false'' %}', N''))) / LEN(N'{% elseif completed == ''false'' %}') = 1;
INSERT @log VALUES ('WorkflowType', 732, 'bool-vs-string', @@ROWCOUNT);
UPDATE WorkflowType SET [NoActionMessage] = REPLACE(REPLACE([NoActionMessage], N'{% if completed == ''true'' %}', N'{% if completed %}'), N'{% elseif completed == ''false'' %}', N'{% else %}')
WHERE [Id] = 733
  AND (LEN([NoActionMessage]) - LEN(REPLACE([NoActionMessage], N'{% if completed == ''true'' %}', N''))) / LEN(N'{% if completed == ''true'' %}') = 1
  AND (LEN([NoActionMessage]) - LEN(REPLACE([NoActionMessage], N'{% elseif completed == ''false'' %}', N''))) / LEN(N'{% elseif completed == ''false'' %}') = 1;
INSERT @log VALUES ('WorkflowType', 733, 'bool-vs-string', @@ROWCOUNT);
UPDATE WorkflowType SET [NoActionMessage] = REPLACE(REPLACE([NoActionMessage], N'{% if completed == ''true'' %}', N'{% if completed %}'), N'{% elseif completed == ''false'' %}', N'{% else %}')
WHERE [Id] = 734
  AND (LEN([NoActionMessage]) - LEN(REPLACE([NoActionMessage], N'{% if completed == ''true'' %}', N''))) / LEN(N'{% if completed == ''true'' %}') = 1
  AND (LEN([NoActionMessage]) - LEN(REPLACE([NoActionMessage], N'{% elseif completed == ''false'' %}', N''))) / LEN(N'{% elseif completed == ''false'' %}') = 1;
INSERT @log VALUES ('WorkflowType', 734, 'bool-vs-string', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = REPLACE(REPLACE([Value], N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}', N'{% assign EventContact = Workflow | Attribute:''StaffContactPerson'', ''Object'' %}'), N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}', N'{% assign Initiator = Workflow | Attribute:''EventInitiator'', ''Object'' %}')
WHERE [Id] = 119518134
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}', N''))) / LEN(N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}', N''))) / LEN(N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}') = 1;
INSERT @log VALUES ('AttributeValue', 119518134, 'mustache-in-assign', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = REPLACE(REPLACE([Value], N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}', N'{% assign EventContact = Workflow | Attribute:''StaffContactPerson'', ''Object'' %}'), N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}', N'{% assign Initiator = Workflow | Attribute:''EventInitiator'', ''Object'' %}')
WHERE [Id] = 119518144
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}', N''))) / LEN(N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}', N''))) / LEN(N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}') = 1;
INSERT @log VALUES ('AttributeValue', 119518144, 'mustache-in-assign', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = REPLACE(REPLACE([Value], N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}', N'{% assign EventContact = Workflow | Attribute:''StaffContactPerson'', ''Object'' %}'), N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}', N'{% assign Initiator = Workflow | Attribute:''EventInitiator'', ''Object'' %}')
WHERE [Id] = 165745851
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}', N''))) / LEN(N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}', N''))) / LEN(N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}') = 1;
INSERT @log VALUES ('AttributeValue', 165745851, 'mustache-in-assign', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = REPLACE(REPLACE([Value], N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}', N'{% assign EventContact = Workflow | Attribute:''StaffContactPerson'', ''Object'' %}'), N'{% assign ChildcareContact = {{Workflow | Attribute:''ChildcareContactPerson'', ''Object''}} %}', N'{% assign ChildcareContact = Workflow | Attribute:''ChildcareContactPerson'', ''Object'' %}')
WHERE [Id] = 175793856
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}', N''))) / LEN(N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign ChildcareContact = {{Workflow | Attribute:''ChildcareContactPerson'', ''Object''}} %}', N''))) / LEN(N'{% assign ChildcareContact = {{Workflow | Attribute:''ChildcareContactPerson'', ''Object''}} %}') = 1;
INSERT @log VALUES ('AttributeValue', 175793856, 'mustache-in-assign', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = REPLACE(REPLACE([Value], N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}', N'{% assign EventContact = Workflow | Attribute:''StaffContactPerson'', ''Object'' %}'), N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}', N'{% assign Initiator = Workflow | Attribute:''EventInitiator'', ''Object'' %}')
WHERE [Id] = 181933899
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}', N''))) / LEN(N'{% assign EventContact = {{Workflow | Attribute:''StaffContactPerson'', ''Object''}} %}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}', N''))) / LEN(N'{% assign Initiator = {{Workflow | Attribute:''EventInitiator'', ''Object''}} %}') = 1;
INSERT @log VALUES ('AttributeValue', 181933899, 'mustache-in-assign', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = N'{%- capture bsq -%}\"{%- endcapture -%}' + REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([Value], N'"Name": "{{g.Name}}"', N'"Name": "{{g.Name | Replace:''"'',bsq}}"'), N'"Title": "{{g.Title}}"', N'"Title": "{{g.Title | Replace:''"'',bsq}}"'), N'"CampusName": "{{g.CampusName}}"', N'"CampusName": "{{g.CampusName | Replace:''"'',bsq}}"'), N'"MeetingLocation": "{{g.MeetingLocation}}"', N'"MeetingLocation": "{{g.MeetingLocation | Replace:''"'',bsq}}"'), N'"CustomSchedule": "{{g.CustomSchedule}}"', N'"CustomSchedule": "{{g.CustomSchedule | Replace:''"'',bsq}}"')
WHERE [Id] = 145692343
  AND (LEN([Value]) - LEN(REPLACE([Value], N'"Name": "{{g.Name}}"', N''))) / LEN(N'"Name": "{{g.Name}}"') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'"Title": "{{g.Title}}"', N''))) / LEN(N'"Title": "{{g.Title}}"') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'"CampusName": "{{g.CampusName}}"', N''))) / LEN(N'"CampusName": "{{g.CampusName}}"') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'"MeetingLocation": "{{g.MeetingLocation}}"', N''))) / LEN(N'"MeetingLocation": "{{g.MeetingLocation}}"') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'"CustomSchedule": "{{g.CustomSchedule}}"', N''))) / LEN(N'"CustomSchedule": "{{g.CustomSchedule}}"') = 1
  AND CHARINDEX(N'capture bsq', [Value]) = 0;
INSERT @log VALUES ('AttributeValue', 145692343, 'json-escape', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = N'{%- capture bsq -%}\"{%- endcapture -%}' + REPLACE(REPLACE(REPLACE([Value], N'"Title": "{{g.Title}}"', N'"Title": "{{g.Title | Replace:''"'',bsq}}"'), N'"CampusName": "{{g.CampusName}}"', N'"CampusName": "{{g.CampusName | Replace:''"'',bsq}}"'), N'"MeetingLocation": "{{g.MeetingLocation}}"', N'"MeetingLocation": "{{g.MeetingLocation | Replace:''"'',bsq}}"')
WHERE [Id] = 328460478
  AND (LEN([Value]) - LEN(REPLACE([Value], N'"Title": "{{g.Title}}"', N''))) / LEN(N'"Title": "{{g.Title}}"') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'"CampusName": "{{g.CampusName}}"', N''))) / LEN(N'"CampusName": "{{g.CampusName}}"') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'"MeetingLocation": "{{g.MeetingLocation}}"', N''))) / LEN(N'"MeetingLocation": "{{g.MeetingLocation}}"') = 1
  AND CHARINDEX(N'capture bsq', [Value]) = 0;
INSERT @log VALUES ('AttributeValue', 328460478, 'json-escape', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = N'{%- capture bsq -%}\"{%- endcapture -%}' + REPLACE(REPLACE([Value], N'"Title": "{{g.Title}}"', N'"Title": "{{g.Title | Replace:''"'',bsq}}"'), N'"CampusName": "{{g.CampusName}}"', N'"CampusName": "{{g.CampusName | Replace:''"'',bsq}}"')
WHERE [Id] = 340611135
  AND (LEN([Value]) - LEN(REPLACE([Value], N'"Title": "{{g.Title}}"', N''))) / LEN(N'"Title": "{{g.Title}}"') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'"CampusName": "{{g.CampusName}}"', N''))) / LEN(N'"CampusName": "{{g.CampusName}}"') = 1
  AND CHARINDEX(N'capture bsq', [Value]) = 0;
INSERT @log VALUES ('AttributeValue', 340611135, 'json-escape', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = REPLACE([Value], N'{%- assign same = d | RegExMatch:''^([0-9])\1\1\1\1\1\1\1\1\1$'' -%}', N'{%- capture reSame -%}^([0-9])\1\1\1\1\1\1\1\1\1${%- endcapture -%}{%- assign same = d | RegExMatch:reSame -%}')
WHERE [Id] = 449094742
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{%- assign same = d | RegExMatch:''^([0-9])\1\1\1\1\1\1\1\1\1$'' -%}', N''))) / LEN(N'{%- assign same = d | RegExMatch:''^([0-9])\1\1\1\1\1\1\1\1\1$'' -%}') = 1;
INSERT @log VALUES ('AttributeValue', 449094742, 'regex-backref-capture', @@ROWCOUNT);

UPDATE l SET [Rows] = -1 FROM @log l WHERE l.[Rows] = 0 AND NOT EXISTS (
    SELECT 1 FROM ReportField x WHERE l.Tbl = 'ReportField' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM HtmlContent x WHERE l.Tbl = 'HtmlContent' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM WorkflowType x WHERE l.Tbl = 'WorkflowType' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM AttributeValue x WHERE l.Tbl = 'AttributeValue' AND x.Id = l.Id);

SELECT Tbl, COUNT(*) Stmts, SUM(CASE WHEN [Rows] = 1 THEN 1 ELSE 0 END) Updated, SUM(CASE WHEN [Rows] = -1 THEN 1 ELSE 0 END) Absent,
       SUM(CASE WHEN [Rows] NOT IN (1, -1) THEN 1 ELSE 0 END) Problems FROM @log GROUP BY Tbl;
SELECT * FROM @log WHERE [Rows] <> 1 ORDER BY Tbl, Id;
IF EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1)) PRINT 'WARNING: some statements did not update exactly one row - review before committing.';
IF @DryRun = 0 AND EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1))
BEGIN ROLLBACK; THROW 50000, 'ROCK9086 pass 7: a guarded update did not match exactly one row; nothing committed.', 1; END

-- verify: none of the old forms remain
SELECT 'ReportField' Tbl, COUNT(*) StillOld FROM ReportField WHERE Selection LIKE '%forloop.rindex > 1%'
UNION ALL SELECT 'HtmlContent', COUNT(*) FROM HtmlContent WHERE Id = 12894 AND (Content LIKE '%hideTitle == false%' OR Content LIKE '%roundHeaderImage == true %')
UNION ALL SELECT 'WorkflowType', COUNT(*) FROM WorkflowType WHERE Id IN (47, 724, 732, 733, 734) AND NoActionMessage LIKE '%completed == ''false''%'
UNION ALL SELECT 'AttributeValue', COUNT(*) FROM AttributeValue WHERE Id IN (119518134, 119518144, 165745851, 175793856, 181933899, 145692343, 328460478, 340611135, 449094742)
    AND (Value LIKE '%= {{Workflow |%' OR Value LIKE '%"Name": "{{g.Name}}"%' OR Value LIKE '%"Title": "{{g.Title}}"%' OR Value LIKE '%RegExMatch:''^([[]0-9])%');

IF @DryRun = 1 BEGIN ROLLBACK; PRINT 'Dry run - rolled back.'; END ELSE BEGIN COMMIT; PRINT 'Committed. Now clear the Rock cache.'; END
