-- ROCK9086 pass 9: rows production reported under Fluid verification 16:45-20:10 on 2026-09-25 (after 010/011).
-- Generated by gen_012.py from the live prod values; every REPLACE was checked against them before writing this file.
-- Same shape as 005-011: guarded update per row, @DryRun = 1 rolls back, live run is all-or-nothing, backups to
-- dbo._ROCK9086_LavaBackup, rows absent from the target database log -1. Clear the Rock cache afterwards.
--
-- HtmlContent 10753 (/ministries/college-age)   nested {% comment %}: Fluid ends at the first endcomment -> "Unknown tag
--                                                'endcomment'". Inner comment tags dropped, outer kept (whole value set,
--                                                guarded by the SHA-256 of the exact current value).
-- HtmlContent 10536 (/communityengagement)       {% if (forloop.rindex0 == 0 %} - parens + Fluid's reversed rindex0.
--                                                DotLiquid only ever took the last-item branch -> {% if forloop.last %}.
-- SystemCommunication 9 (Workflow Form           the link was mangled by an HTML editor on 2020-11-20
-- Notification)                                  ({{ ' global'="" |="" ...) -> Fluid parse error; restored to the stock line.
--                                                BEHAVIOUR CHANGE: the "requires action" link works again on both engines.
-- AttributeValue 419773844, 25012462             {% assign textSize = Workflow | Attribute:'...Text' %}{% if textSize > 0 %}
-- (reference "Create the PDF")                   compares text to 0: DotLiquid true when non-empty, Fluid never -> | Size.
-- AttributeValue 199751449 (page 3040            uppercase AND (DotLiquid ignores everything after it) and parens in elseif.
-- Baptisms By Campus, Date & Age)                BEHAVIOUR CHANGE: the age filter now works as written; on DotLiquid it
--                                                emitted `age <= CAST('' AS INT)` whenever MaxAgeRange was blank.
-- Verified with LavaProbe (M1-M3, gen_cases21 matrix, probe-cases22).
SET NOCOUNT ON; SET XACT_ABORT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
DECLARE @DryRun bit = 1;
DECLARE @log TABLE (Tbl sysname, Id int, FixRule varchar(40), [Rows] int);
BEGIN TRAN;

IF OBJECT_ID('dbo._ROCK9086_LavaBackup') IS NULL
    CREATE TABLE dbo._ROCK9086_LavaBackup (Tbl sysname NOT NULL, Id int NOT NULL, Col sysname NOT NULL, OldValue nvarchar(max) NULL, BackedUpAt datetime NOT NULL DEFAULT GETDATE());

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM AttributeValue x WHERE x.[Id] IN (199751449, 25012462, 419773844)
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id] AND b.Col = 'Value');
INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'HtmlContent', x.[Id], 'Content', x.[Content] FROM HtmlContent x WHERE x.[Id] IN (10536, 10753)
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'HtmlContent' AND b.Id = x.[Id] AND b.Col = 'Content');
INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'SystemCommunication', x.[Id], 'Body', x.[Body] FROM SystemCommunication x WHERE x.[Id] IN (9)
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'SystemCommunication' AND b.Id = x.[Id] AND b.Col = 'Body');

UPDATE HtmlContent SET [Content] = CAST(N'<section id="WhatsNextForYou">
    <div class="container g-padding-t-50--md">

        <div class="row">
            <div class="col-sm-12 text-center">
                <br>
                <br>
                <br>
                <h1 class=""><strong class="g-font-family--secondary">What''s Next For You?</strong></h1>
                <h5>Explore our disciple-making pathway</h5>
                <br>
                <br>
                <br>
            </div>
        </div>

        <div class="row g-padding-y-20--xs">
            <div class="col-xs-12 col-md-4 event-calendar">
                <div class="clearfix card g-margin-x-50--xs g-margin-x-20--md">
                    <div class="text-center g-padding-x-60--xs g-padding-y-60--xs">
                        <h3 class="g-font-family--secondary g-font-weight--600" style="margin-bottom: 5px;">CONNECT</h3>
                        <p class="g-font-weight--600 g-margin-b-0--xs">Start here.</p>
                    </div>
                    <div class="col-xs-12 g-padding-x-60--xs g-padding-y-60--xs g-margin-t-0--xs g-hor-divider__solid__t--gray-lightest">
                        <p class="caption">Do you want to get connected to one of College Age Ministries? Here are few ways that you can do that. Send an email to <a href="mailto:collegeministry@secc.org"> College Ministry</a> and one of our staff will reach out to you ASAP. Follow us on <a href="https://www.instagram.com/southeastcam/">Instagram.com/southeastcam </a> 
                            <Br><Br>

                             We post often about what''s going on in CAM. In the story section of our Instagram page there''s a tab titled "campuses" where you''ll find details and contact info for CAM expressions at different SECC campuses, so you can get connected to a campus near you. </p>
                        {%comment %}
                        <div class="readmore_summary_college">
                            <div class="g-padding-b-100--xs">
                                <p>Learn how to get plugged in.</p>
                                <br>
                                
                                <p><strong>SUMMER KICKOFF</strong><br>
                                    Worship, live DJ, free food, and much more! Don''t miss one of the biggest events of the year!
                                </p> 
                                <br>
                                 <p><strong>CAMCHELLA</strong><br>
                                    Music festival vibes with live bands and free food trucks! Nothing beats this night!
                                </p>
                                <br>
                                <p><strong>HANGOUTS</strong><br>
                                    Hangouts happen throughout the whole summer! Make sure to join our text alerts so you don''t miss the fun. Text keyword ' + NCHAR(8220) + N'HANG' + NCHAR(8221) + N' to 555-888 to
                                    stay updated.
                                </p> 
                            </div>
                        </div>
                        {%endcomment %}
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-4 event-calendar">
                <div class="clearfix card g-margin-x-50--xs g-margin-x-20--md">
                    <div class="text-center g-padding-x-60--xs g-padding-y-60--xs">
                        <h3 class="g-font-family--secondary g-font-weight--600" style="margin-bottom: 5px;">BELONG</h3>
                        <p class="g-font-weight--600 g-margin-b-0--xs">Find Community</p>
                    </div>
                    <div class="col-xs-12 g-padding-x-60--xs g-padding-y-60--xs g-margin-t-0--xs g-hor-divider__solid__t--gray-lightest">
                        <p class="caption">We all need a place to belong, people to share life with, and others who are pouring into us. There are so many College Age Ministry opportunities happening throughout the year at many of our SECC campuses and we''d love for you to join us. <br> <br>
                            DM us on <a href="https://www.instagram.com/southeastcam/">Instagram.com/southeastcam</a> or send us an email at <a href="mailto:collegeministry@secc.org">College Ministry</a> so we can help you connect to a CAM Group at one our campuses. </p>
                        {% comment %}
                        <div class="readmore_summary_college">
                            <div class="g-padding-b-100--xs">
                                <p>Learn how to be a disciple.</p>
                                <br>
                                
                                <p><strong>SUMMER GROUPS</strong><br>
                                Summer Groups are the primary way to connect and grow in our ministry this summer. Join us as we study the bold moves of Jesus! To join a group, email Kamille Bayless at <a href="mailto:kbayless@secc.org">kbayless@secc.org</a>.
                                </p>
                                <br>
                                <p><strong>NAVIGATE</strong><br>
                                An interactive study that challenges college-age to follow Jesus in the everyday stuff of life.
                                </p>
                                
                            </div>
                        </div>
                        {% endcomment %}
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-4 event-calendar">
                <div class="clearfix card g-margin-x-50--xs g-margin-x-20--md">
                    <div class="text-center g-padding-x-60--xs g-padding-y-60--xs">
                        <h3 class="g-font-family--secondary g-font-weight--600" style="margin-bottom: 5px;">SERVE</h3>
                        <p class="g-font-weight--600 g-margin-b-0--xs">Be Unleashed</p>
                    </div>
                    <div class="col-xs-12 g-padding-x-60--xs g-padding-y-60--xs g-margin-t-0--xs g-hor-divider__solid__t--gray-lightest">
                        <p class="caption">Jesus calls us to a life of service and we want to be faithful to answer that call. In CAM at Southeast Christian Church we want to unleash you to serve within our Church and our city. Here''s a link to the service opportunities within our Church and our city <a href="https://www.southeastchristian.org/serve">, Serve With Us.</a> Let us help you begin the process of being unleashed!</p>
                        {% comment %}
                        <div class="readmore_summary_college">
                            <div class="g-padding-b-100--xs">
                                <p></p>
                                <br>
                                
                                <p><strong>GROUP LEADER</strong><br>
                                Lead a summer group of 8-10 college-age people as we study the Bold Moves of Jesus together. To lead a group, email Kamille Bayless at <a href="mailto:kbayless@secc.org">kbayless@secc.org</a>.
                                </p>
                                <br>
                                <p><strong>LEADER HANGS</strong><br>
                                Gatherings of all CAM leaders and disciple-makers to hang and examine the disciple-making patterns of Jesus.
                                </p>
                                <br>
                                <p><strong>LEADER RETREAT</strong><br>
                                A short getaway for all CAM disciple-makers to connect and build deeper relationships.
                                
                                </p>
                            </div>
                        </div>
                        {% endcomment %}
                    </div>
                </div>
            </div>
        </div>

        <br>
        <br>
    </div>
</section>' AS nvarchar(max))
WHERE [Id] = 10753 AND HASHBYTES('SHA2_256', [Content]) = 0xC86853A015D6C30D46BFEBFD6DD7A162DB1F3A9DA45E5BD71B2F4A0ACCC9532F AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId);
INSERT @log VALUES ('HtmlContent', 10753, 'nested-comment', @@ROWCOUNT);
UPDATE HtmlContent SET [Content] = REPLACE([Content], N'{% if (forloop.rindex0 == 0 %}<br />{% break %}{% elseif (forloop.rindex0 == 1 and timesCount > 2) %} &amp;{% else %},{% endif %}', N'{% if forloop.last %}<br />{% break %}{% else %},{% endif %}')
WHERE [Id] = 10536
  AND (LEN([Content]) - LEN(REPLACE([Content], N'{% if (forloop.rindex0 == 0 %}<br />{% break %}{% elseif (forloop.rindex0 == 1 and timesCount > 2) %} &amp;{% else %},{% endif %}', N''))) / LEN(N'{% if (forloop.rindex0 == 0 %}<br />{% break %}{% elseif (forloop.rindex0 == 1 and timesCount > 2) %} &amp;{% else %},{% endif %}') = 1 AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId);
INSERT @log VALUES ('HtmlContent', 10536, 'parens-rindex0', @@ROWCOUNT);
UPDATE SystemCommunication SET [Body] = REPLACE([Body], N'<a href=''{{ '' global''="" |="" attribute:''internalapplicationroot''="" }}workflowentry/{{="" workflow.workflowtypeid="" }}?workflowguid="{{" workflow.guid="" }}''="">', N'<a href=''{{ ''Global'' | Attribute:''InternalApplicationRoot'' }}WorkflowEntry/{{ Workflow.WorkflowTypeId }}?WorkflowGuid={{ Workflow.Guid }}''>')
WHERE [Id] = 9
  AND (LEN([Body]) - LEN(REPLACE([Body], N'<a href=''{{ '' global''="" |="" attribute:''internalapplicationroot''="" }}workflowentry/{{="" workflow.workflowtypeid="" }}?workflowguid="{{" workflow.guid="" }}''="">', N''))) / LEN(N'<a href=''{{ '' global''="" |="" attribute:''internalapplicationroot''="" }}workflowentry/{{="" workflow.workflowtypeid="" }}?workflowguid="{{" workflow.guid="" }}''="">') = 1;
INSERT @log VALUES ('SystemCommunication', 9, 'mangled-href', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = REPLACE(REPLACE([Value], N'{% assign textSize = Workflow | Attribute:''ReasontheyShouldNOTVolunteerText'' %}', N'{% assign textSize = Workflow | Attribute:''ReasontheyShouldNOTVolunteerText'' | Size %}'), N'{% assign textSize = Workflow | Attribute:''AnythingElseText'' %}', N'{% assign textSize = Workflow | Attribute:''AnythingElseText'' | Size %}')
WHERE [Id] = 419773844
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign textSize = Workflow | Attribute:''ReasontheyShouldNOTVolunteerText'' %}', N''))) / LEN(N'{% assign textSize = Workflow | Attribute:''ReasontheyShouldNOTVolunteerText'' %}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign textSize = Workflow | Attribute:''AnythingElseText'' %}', N''))) / LEN(N'{% assign textSize = Workflow | Attribute:''AnythingElseText'' %}') = 1;
INSERT @log VALUES ('AttributeValue', 419773844, 'text-vs-zero', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = REPLACE(REPLACE([Value], N'{% assign textSize = Workflow | Attribute:''ReasontheyShouldNOTVolunteerText'' %}', N'{% assign textSize = Workflow | Attribute:''ReasontheyShouldNOTVolunteerText'' | Size %}'), N'{% assign textSize = Workflow | Attribute:''AnythingElseText'' %}', N'{% assign textSize = Workflow | Attribute:''AnythingElseText'' | Size %}')
WHERE [Id] = 25012462
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign textSize = Workflow | Attribute:''ReasontheyShouldNOTVolunteerText'' %}', N''))) / LEN(N'{% assign textSize = Workflow | Attribute:''ReasontheyShouldNOTVolunteerText'' %}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% assign textSize = Workflow | Attribute:''AnythingElseText'' %}', N''))) / LEN(N'{% assign textSize = Workflow | Attribute:''AnythingElseText'' %}') = 1;
INSERT @log VALUES ('AttributeValue', 25012462, 'text-vs-zero', @@ROWCOUNT);
UPDATE AttributeValue SET [Value] = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE([Value], N'{% if MaxDateRange != empty AND MinDateRange != empty  %}', N'{% if MaxDateRange != empty and MinDateRange != empty  %}'), N'{% if MinDateRange != empty AND MaxDateRange == empty%}', N'{% if MinDateRange != empty and MaxDateRange == empty%}'), N'{% if MaxDateRange != empty AND MinDateRange == empty%}', N'{% if MaxDateRange != empty and MinDateRange == empty%}'), N'{% elseif (MinAgeRange != empty AND MaxAgeRange != empty) %}', N'{% elseif MinAgeRange != empty and MaxAgeRange != empty %}'), N'{% elseif (MinAgeRange != empty AND MaxAgeRange == empty) %}', N'{% elseif MinAgeRange != empty and MaxAgeRange == empty %}'), N'{% elseif (MinAgeRange == empty AND MaxAgeRange != empty) %}', N'{% elseif MinAgeRange == empty and MaxAgeRange != empty %}')
WHERE [Id] = 199751449
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% if MaxDateRange != empty AND MinDateRange != empty  %}', N''))) / LEN(N'{% if MaxDateRange != empty AND MinDateRange != empty  %}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% if MinDateRange != empty AND MaxDateRange == empty%}', N''))) / LEN(N'{% if MinDateRange != empty AND MaxDateRange == empty%}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% if MaxDateRange != empty AND MinDateRange == empty%}', N''))) / LEN(N'{% if MaxDateRange != empty AND MinDateRange == empty%}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% elseif (MinAgeRange != empty AND MaxAgeRange != empty) %}', N''))) / LEN(N'{% elseif (MinAgeRange != empty AND MaxAgeRange != empty) %}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% elseif (MinAgeRange != empty AND MaxAgeRange == empty) %}', N''))) / LEN(N'{% elseif (MinAgeRange != empty AND MaxAgeRange == empty) %}') = 1
  AND (LEN([Value]) - LEN(REPLACE([Value], N'{% elseif (MinAgeRange == empty AND MaxAgeRange != empty) %}', N''))) / LEN(N'{% elseif (MinAgeRange == empty AND MaxAgeRange != empty) %}') = 1;
INSERT @log VALUES ('AttributeValue', 199751449, 'upper-AND-parens', @@ROWCOUNT);

UPDATE l SET [Rows] = -1 FROM @log l WHERE l.[Rows] = 0 AND NOT EXISTS (
    SELECT 1 FROM AttributeValue x WHERE l.Tbl = 'AttributeValue' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM HtmlContent x WHERE l.Tbl = 'HtmlContent' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM SystemCommunication x WHERE l.Tbl = 'SystemCommunication' AND x.Id = l.Id);

SELECT * FROM @log ORDER BY Tbl, Id;
IF EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1)) PRINT 'WARNING: some statements did not update exactly one row - review before committing.';
IF @DryRun = 0 AND EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1))
BEGIN ROLLBACK; THROW 50000, 'ROCK9086 pass 9: a guarded update did not match exactly one row; nothing committed.', 1; END

SELECT 'StillOld' Chk,
  (SELECT COUNT(*) FROM HtmlContent WHERE Id = 10536 AND Content LIKE '%{[%] if (forloop.rindex0%') Html10536,
  (SELECT COUNT(*) FROM SystemCommunication WHERE Id = 9 AND Body LIKE '%'' global''=""%') SysComm9,
  (SELECT COUNT(*) FROM AttributeValue WHERE Id IN (419773844, 25012462) AND Value LIKE '%Text'' [%]}{[%] if textSize > 0%') RefPdf,
  (SELECT COUNT(*) FROM AttributeValue WHERE Id = 199751449 AND Value COLLATE Latin1_General_CS_AS LIKE '%empty AND %') Bap3040,
  (SELECT (LEN(Content) - LEN(REPLACE(Content, N'endcomment', N''))) / 10 FROM HtmlContent WHERE Id = 10753) EndCommentsIn10753;

IF @DryRun = 1 BEGIN ROLLBACK; PRINT 'Dry run - rolled back.'; END ELSE BEGIN COMMIT; PRINT 'Committed. Now clear the Rock cache.'; END
