-- ROCK9086 pass 11b (generated by gen_015.py): WorkflowType 456 "The Unified Connection Card" SummaryViewText, shown on
-- /Workflow/{id}. `{% if person != null && person != empty %}` is a Fluid parse error. DotLiquid evaluates only the first
-- clause; `person` is `Attribute:'Person','Object'` (a Person or null, never ''), so `and` gives the same result
-- (LavaProbe cases 32 E1-E4). Same guarded shape as 014.
SET NOCOUNT ON; SET XACT_ABORT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
DECLARE @DryRun bit = 1;
DECLARE @log TABLE (Tbl sysname, Id int, FixRule varchar(40), [Rows] int);
DECLARE @avkeys TABLE (Id int, AttributeId int, EntityId int);
INSERT @avkeys VALUES (3752511, 1016, 1139), (3752514, 1019, 1139), (3889252, 1027, 1173), (51107841, 1027, 4007), (55093101, 81470, 4501), (58019746, 81470, 4608), (71943274, 1019, 4807), (71943275, 1016, 4807), (101737557, 1201, 6335), (119518117, 1019, 7584), (119518133, 1019, 7589), (119518134, 1016, 7589), (181166313, 1019, 8032), (181933899, 1016, 8034), (211932365, 1201, 6994), (418179915, 17501, 22117), (419773863, 17501, 24872), (446668184, 1019, 76744), (446668185, 1016, 76744);
BEGIN TRAN;

IF OBJECT_ID('dbo._ROCK9086_LavaBackup') IS NULL
    CREATE TABLE dbo._ROCK9086_LavaBackup (Tbl sysname NOT NULL, Id int NOT NULL, Col sysname NOT NULL, OldValue nvarchar(max) NULL, BackedUpAt datetime NOT NULL DEFAULT GETDATE());

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'WorkflowType', x.[Id], 'SummaryViewText', x.[SummaryViewText] FROM [WorkflowType] x WHERE x.[Id] = 456
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'WorkflowType' AND b.Id = x.[Id] AND b.Col = 'SummaryViewText');
UPDATE [WorkflowType] SET [SummaryViewText] = REPLACE([SummaryViewText], N'{% if person != null && person != empty %}', N'{% if person != null and person != empty %}')
WHERE [Id] = 456
  AND (DATALENGTH([SummaryViewText]) - DATALENGTH(REPLACE([SummaryViewText], N'{% if person != null && person != empty %}', N''))) / DATALENGTH(N'{% if person != null && person != empty %}') = 1;
INSERT @log VALUES ('WorkflowType', 456, 'ampamp', @@ROWCOUNT);

UPDATE l SET [Rows] = -1 FROM @log l WHERE l.[Rows] = 0 AND NOT EXISTS (
    SELECT 1 FROM WorkflowType x WHERE l.Tbl = 'WorkflowType' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM HtmlContent x WHERE l.Tbl = 'HtmlContent' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM WorkflowActionForm x WHERE l.Tbl = 'WorkflowActionForm' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM SystemCommunication x WHERE l.Tbl = 'SystemCommunication' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM AttributeValue x JOIN @avkeys k ON k.Id = x.Id AND k.AttributeId = x.AttributeId AND k.EntityId = x.EntityId
        WHERE l.Tbl = 'AttributeValue' AND x.Id = l.Id);
SELECT * FROM @log ORDER BY Tbl, Id;
IF EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1)) PRINT 'WARNING: some statements did not update exactly one row - review before committing.';
IF @DryRun = 0 AND EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1))
BEGIN ROLLBACK; THROW 50000, 'ROCK9086 pass 11b: a guarded update did not match exactly one row; nothing committed.', 1; END

SELECT 'WorkflowType' Tbl, 456 Id, CASE WHEN CHARINDEX(N'{% if person != null && person != empty %}' COLLATE Latin1_General_CS_AS, [SummaryViewText] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [WorkflowType] WHERE [Id] = 456;

IF @DryRun = 1 BEGIN ROLLBACK; PRINT 'Dry run - rolled back.'; END ELSE BEGIN COMMIT; PRINT 'Committed. Now clear the Rock cache.'; END
