-- ROCK9086 pass 12b (generated by gen_017.py): CommunicationTemplate 4 "Neighborhood Group - Recommit Final Reminder".
-- `rckipid={{%20Person.UrlEncodedKey%20}}` is a Fluid parse error (the whole email fails); DotLiquid renders the key empty.
-- The link points at Webflow, so no Rock login token: the tag is removed and the output matches DotLiquid today.
-- Same guarded shape as 014-016. Clear the Rock cache after.
SET NOCOUNT ON; SET XACT_ABORT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
DECLARE @DryRun bit = 1;
DECLARE @log TABLE (Tbl sysname, Id int, FixRule varchar(40), [Rows] int);
DECLARE @avkeys TABLE (Id int, AttributeId int, EntityId int);
INSERT @avkeys VALUES (0, 0, 0);
BEGIN TRAN;

IF OBJECT_ID('dbo._ROCK9086_LavaBackup') IS NULL
    CREATE TABLE dbo._ROCK9086_LavaBackup (Tbl sysname NOT NULL, Id int NOT NULL, Col sysname NOT NULL, OldValue nvarchar(max) NULL, BackedUpAt datetime NOT NULL DEFAULT GETDATE());

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'CommunicationTemplate', x.[Id], 'Message', x.[Message] FROM [CommunicationTemplate] x WHERE x.[Id] = 4
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'CommunicationTemplate' AND b.Id = x.[Id] AND b.Col = 'Message');
UPDATE [CommunicationTemplate] SET [Message] = REPLACE([Message], N'rckipid={{%20Person.UrlEncodedKey%20}}', N'rckipid=')
WHERE [Id] = 4
  AND (DATALENGTH([Message]) - DATALENGTH(REPLACE([Message], N'rckipid={{%20Person.UrlEncodedKey%20}}', N''))) / DATALENGTH(N'rckipid={{%20Person.UrlEncodedKey%20}}') = 1;
INSERT @log VALUES ('CommunicationTemplate', 4, 'urlencoded-mustache', @@ROWCOUNT);

UPDATE l SET [Rows] = -1 FROM @log l WHERE l.[Rows] = 0 AND NOT EXISTS (
    SELECT 1 FROM WorkflowType x WHERE l.Tbl = 'WorkflowType' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM HtmlContent x WHERE l.Tbl = 'HtmlContent' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM WorkflowActionForm x WHERE l.Tbl = 'WorkflowActionForm' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM SystemCommunication x WHERE l.Tbl = 'SystemCommunication' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM Block x WHERE l.Tbl = 'Block' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM CommunicationTemplate x WHERE l.Tbl = 'CommunicationTemplate' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM ReportField x WHERE l.Tbl = 'ReportField' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM AttributeValue x JOIN @avkeys k ON k.Id = x.Id AND k.AttributeId = x.AttributeId AND k.EntityId = x.EntityId
        WHERE l.Tbl = 'AttributeValue' AND x.Id = l.Id);
SELECT * FROM @log ORDER BY Tbl, Id;
IF EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1)) PRINT 'WARNING: some statements did not update exactly one row - review before committing.';
IF @DryRun = 0 AND EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1))
BEGIN ROLLBACK; THROW 50000, 'ROCK9086 pass 12b: a guarded update did not match exactly one row; nothing committed.', 1; END

SELECT 'CommunicationTemplate' Tbl, 4 Id, CASE WHEN CHARINDEX(N'rckipid={{%20Person.UrlEncodedKey%20}}' COLLATE Latin1_General_CS_AS, [Message] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [CommunicationTemplate] WHERE [Id] = 4;

IF @DryRun = 1 BEGIN ROLLBACK; PRINT 'Dry run - rolled back.'; END ELSE BEGIN COMMIT; PRINT 'Committed. Now clear the Rock cache.'; END
