-- ROCK9086 pass 13 (generated by gen_018.py): rows production logged under Fluid verification 2026-09-30..10-07.
-- Behaviour changes on DotLiquid (same class as 016, approved 2026-09-30):
--   occurred-if (Event Request - Internal 72: summary view and 4 emails): a filter in an if was always true on
--     DotLiquid, so "When/Where was it held" always showed; now only when the event occurred before.
--   reopened-if (RSVP Weekend Prayer follow-up emails, prod only): "Their card had been closed" showed in every
--     email; now only when the card was reopened.
--   report-if (report 1532 Security Check column): "Attendance verified more than 6 months ago" showed for everyone
--     (filter chain inside if); now only past 186 days. The parenthesised or is a Fluid parse error, same on DotLiquid.
-- Same output on DotLiquid: parens-if (Sports & Fitness training Run Lava action), encoded-lte (2018 MIX camp
--   pages 1159-1164), int-vs-empty (Pastoral Care Nursing Home List: 0 == '' and bool == 'false' are TRUE on Fluid,
--   so a 0 visit count went blank and the Communion icon flipped; DotLiquid output unchanged).
--   LavaProbe cases 38, P1-P10, Q1-Q11.
-- Guarded REPLACE per row, @DryRun = 1 rolls back, the live run is all-or-nothing, one backup per row to
-- dbo._ROCK9086_LavaBackup, rows absent from the target database log -1. Clear the Rock cache after.
SET NOCOUNT ON; SET XACT_ABORT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
DECLARE @DryRun bit = 1;
DECLARE @log TABLE (Tbl sysname, Id int, FixRule varchar(40), [Rows] int);
DECLARE @avkeys TABLE (Id int, AttributeId int, EntityId int);
INSERT @avkeys VALUES (3094280, 1016, 814), (80610811, 1016, 6340), (80610821, 1016, 6343), (82143392, 1016, 6590), (206537195, 17501, 8357), (418777152, 1201, 9054), (449129641, 1016, 76889), (449130783, 1016, 76902), (449130791, 1016, 76903);
BEGIN TRAN;

IF OBJECT_ID('dbo._ROCK9086_LavaBackup') IS NULL
    CREATE TABLE dbo._ROCK9086_LavaBackup (Tbl sysname NOT NULL, Id int NOT NULL, Col sysname NOT NULL, OldValue nvarchar(max) NULL, BackedUpAt datetime NOT NULL DEFAULT GETDATE());

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'ReportField', x.[Id], 'Selection', x.[Selection] FROM [ReportField] x WHERE x.[Id] = 71196
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'ReportField' AND b.Id = x.[Id] AND b.Col = 'Selection');
UPDATE [ReportField] SET [Selection] = REPLACE(REPLACE([Selection], N'{% if (CriminalCheckStatus == ''Approved'') or (CriminalCheckStatus == ''Reapproved'') %}', N'{% if CriminalCheckStatus == ''Approved'' or CriminalCheckStatus == ''Reapproved'' %}'), N'{% if  Attendance1stVerifiedDate| Date:''M/d/yyyy'' | DateDiff:''Now'',''d'' > 186 %}', N'{% assign daysSinceFirstAttend = Attendance1stVerifiedDate | DateDiff:''Now'',''d'' %}{% if daysSinceFirstAttend > 186 %}')
WHERE [Id] = 71196
  AND (DATALENGTH([Selection]) - DATALENGTH(REPLACE([Selection], N'{% if (CriminalCheckStatus == ''Approved'') or (CriminalCheckStatus == ''Reapproved'') %}', N''))) / DATALENGTH(N'{% if (CriminalCheckStatus == ''Approved'') or (CriminalCheckStatus == ''Reapproved'') %}') = 1
  AND (DATALENGTH([Selection]) - DATALENGTH(REPLACE([Selection], N'{% if  Attendance1stVerifiedDate| Date:''M/d/yyyy'' | DateDiff:''Now'',''d'' > 186 %}', N''))) / DATALENGTH(N'{% if  Attendance1stVerifiedDate| Date:''M/d/yyyy'' | DateDiff:''Now'',''d'' > 186 %}') = 1;
INSERT @log VALUES ('ReportField', 71196, 'report-if', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'WorkflowType', x.[Id], 'SummaryViewText', x.[SummaryViewText] FROM [WorkflowType] x WHERE x.[Id] = 72
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'WorkflowType' AND b.Id = x.[Id] AND b.Col = 'SummaryViewText');
UPDATE [WorkflowType] SET [SummaryViewText] = REPLACE([SummaryViewText], N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}', N'{% assign occurredBefore = Workflow | Attribute:''HasItOccurredBefore'',''RawValue'' %}{% if occurredBefore == ''True'' %}')
WHERE [Id] = 72
  AND (DATALENGTH([SummaryViewText]) - DATALENGTH(REPLACE([SummaryViewText], N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}', N''))) / DATALENGTH(N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}') = 1;
INSERT @log VALUES ('WorkflowType', 72, 'occurred-if', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM [AttributeValue] x WHERE x.[Id] = 3094280 AND x.[AttributeId] = 1016 AND x.[EntityId] = 814
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id] AND b.Col = 'Value');
UPDATE [AttributeValue] SET [Value] = REPLACE([Value], N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}', N'{% assign occurredBefore = Workflow | Attribute:''HasItOccurredBefore'',''RawValue'' %}{% if occurredBefore == ''True'' %}')
WHERE [Id] = 3094280 AND [AttributeId] = 1016 AND [EntityId] = 814
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}', N''))) / DATALENGTH(N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}') = 1;
INSERT @log VALUES ('AttributeValue', 3094280, 'occurred-if', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM [AttributeValue] x WHERE x.[Id] = 80610811 AND x.[AttributeId] = 1016 AND x.[EntityId] = 6340
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id] AND b.Col = 'Value');
UPDATE [AttributeValue] SET [Value] = REPLACE([Value], N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}', N'{% assign occurredBefore = Workflow | Attribute:''HasItOccurredBefore'',''RawValue'' %}{% if occurredBefore == ''True'' %}')
WHERE [Id] = 80610811 AND [AttributeId] = 1016 AND [EntityId] = 6340
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}', N''))) / DATALENGTH(N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}') = 1;
INSERT @log VALUES ('AttributeValue', 80610811, 'occurred-if', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM [AttributeValue] x WHERE x.[Id] = 80610821 AND x.[AttributeId] = 1016 AND x.[EntityId] = 6343
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id] AND b.Col = 'Value');
UPDATE [AttributeValue] SET [Value] = REPLACE([Value], N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}', N'{% assign occurredBefore = Workflow | Attribute:''HasItOccurredBefore'',''RawValue'' %}{% if occurredBefore == ''True'' %}')
WHERE [Id] = 80610821 AND [AttributeId] = 1016 AND [EntityId] = 6343
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}', N''))) / DATALENGTH(N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}') = 1;
INSERT @log VALUES ('AttributeValue', 80610821, 'occurred-if', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM [AttributeValue] x WHERE x.[Id] = 82143392 AND x.[AttributeId] = 1016 AND x.[EntityId] = 6590
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id] AND b.Col = 'Value');
UPDATE [AttributeValue] SET [Value] = REPLACE([Value], N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}', N'{% assign occurredBefore = Workflow | Attribute:''HasItOccurredBefore'',''RawValue'' %}{% if occurredBefore == ''True'' %}')
WHERE [Id] = 82143392 AND [AttributeId] = 1016 AND [EntityId] = 6590
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}', N''))) / DATALENGTH(N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}') = 1;
INSERT @log VALUES ('AttributeValue', 82143392, 'occurred-if', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM [AttributeValue] x WHERE x.[Id] = 206537195 AND x.[AttributeId] = 17501 AND x.[EntityId] = 8357
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id] AND b.Col = 'Value');
UPDATE [AttributeValue] SET [Value] = REPLACE([Value], N'{% if (submitorPersonName != participantPersonName) and (minorStatus != ''Yes'') %}', N'{% if submitorPersonName != participantPersonName and minorStatus != ''Yes'' %}')
WHERE [Id] = 206537195 AND [AttributeId] = 17501 AND [EntityId] = 8357
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if (submitorPersonName != participantPersonName) and (minorStatus != ''Yes'') %}', N''))) / DATALENGTH(N'{% if (submitorPersonName != participantPersonName) and (minorStatus != ''Yes'') %}') = 1;
INSERT @log VALUES ('AttributeValue', 206537195, 'parens-if', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM [AttributeValue] x WHERE x.[Id] = 449129641 AND x.[AttributeId] = 1016 AND x.[EntityId] = 76889
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id] AND b.Col = 'Value');
UPDATE [AttributeValue] SET [Value] = REPLACE([Value], N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}', N'{% assign cardReopened = Workflow | Attribute:''CardReopened'' %}{% if cardReopened == ''Yes'' %}')
WHERE [Id] = 449129641 AND [AttributeId] = 1016 AND [EntityId] = 76889
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}', N''))) / DATALENGTH(N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}') = 1;
INSERT @log VALUES ('AttributeValue', 449129641, 'reopened-if', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM [AttributeValue] x WHERE x.[Id] = 449130783 AND x.[AttributeId] = 1016 AND x.[EntityId] = 76902
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id] AND b.Col = 'Value');
UPDATE [AttributeValue] SET [Value] = REPLACE([Value], N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}', N'{% assign cardReopened = Workflow | Attribute:''CardReopened'' %}{% if cardReopened == ''Yes'' %}')
WHERE [Id] = 449130783 AND [AttributeId] = 1016 AND [EntityId] = 76902
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}', N''))) / DATALENGTH(N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}') = 1;
INSERT @log VALUES ('AttributeValue', 449130783, 'reopened-if', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM [AttributeValue] x WHERE x.[Id] = 449130791 AND x.[AttributeId] = 1016 AND x.[EntityId] = 76903
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id] AND b.Col = 'Value');
UPDATE [AttributeValue] SET [Value] = REPLACE([Value], N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}', N'{% assign cardReopened = Workflow | Attribute:''CardReopened'' %}{% if cardReopened == ''Yes'' %}')
WHERE [Id] = 449130791 AND [AttributeId] = 1016 AND [EntityId] = 76903
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}', N''))) / DATALENGTH(N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}') = 1;
INSERT @log VALUES ('AttributeValue', 449130791, 'reopened-if', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'HtmlContent', x.[Id], 'Content', x.[Content] FROM [HtmlContent] x WHERE x.[Id] = 546
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'HtmlContent' AND b.Id = x.[Id] AND b.Col = 'Content');
UPDATE [HtmlContent] SET [Content] = REPLACE([Content], N'{% if registrationClosed &lt;= currentDate %}', N'{% if registrationClosed <= currentDate %}')
WHERE [Id] = 546
  AND (DATALENGTH([Content]) - DATALENGTH(REPLACE([Content], N'{% if registrationClosed &lt;= currentDate %}', N''))) / DATALENGTH(N'{% if registrationClosed &lt;= currentDate %}') = 1
  AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId);
INSERT @log VALUES ('HtmlContent', 546, 'encoded-lte', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'HtmlContent', x.[Id], 'Content', x.[Content] FROM [HtmlContent] x WHERE x.[Id] = 547
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'HtmlContent' AND b.Id = x.[Id] AND b.Col = 'Content');
UPDATE [HtmlContent] SET [Content] = REPLACE([Content], N'{% if releaseRegistration &lt;= currentDate %}', N'{% if releaseRegistration <= currentDate %}')
WHERE [Id] = 547
  AND (DATALENGTH([Content]) - DATALENGTH(REPLACE([Content], N'{% if releaseRegistration &lt;= currentDate %}', N''))) / DATALENGTH(N'{% if releaseRegistration &lt;= currentDate %}') = 1
  AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId);
INSERT @log VALUES ('HtmlContent', 547, 'encoded-lte', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'HtmlContent', x.[Id], 'Content', x.[Content] FROM [HtmlContent] x WHERE x.[Id] = 548
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'HtmlContent' AND b.Id = x.[Id] AND b.Col = 'Content');
UPDATE [HtmlContent] SET [Content] = REPLACE([Content], N'{% if releaseRegistration &lt;= currentDate %}', N'{% if releaseRegistration <= currentDate %}')
WHERE [Id] = 548
  AND (DATALENGTH([Content]) - DATALENGTH(REPLACE([Content], N'{% if releaseRegistration &lt;= currentDate %}', N''))) / DATALENGTH(N'{% if releaseRegistration &lt;= currentDate %}') = 1
  AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId);
INSERT @log VALUES ('HtmlContent', 548, 'encoded-lte', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'HtmlContent', x.[Id], 'Content', x.[Content] FROM [HtmlContent] x WHERE x.[Id] = 550
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'HtmlContent' AND b.Id = x.[Id] AND b.Col = 'Content');
UPDATE [HtmlContent] SET [Content] = REPLACE([Content], N'{% if releaseRegistration &lt;= currentDate %}', N'{% if releaseRegistration <= currentDate %}')
WHERE [Id] = 550
  AND (DATALENGTH([Content]) - DATALENGTH(REPLACE([Content], N'{% if releaseRegistration &lt;= currentDate %}', N''))) / DATALENGTH(N'{% if releaseRegistration &lt;= currentDate %}') = 1
  AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId);
INSERT @log VALUES ('HtmlContent', 550, 'encoded-lte', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'HtmlContent', x.[Id], 'Content', x.[Content] FROM [HtmlContent] x WHERE x.[Id] = 554
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'HtmlContent' AND b.Id = x.[Id] AND b.Col = 'Content');
UPDATE [HtmlContent] SET [Content] = REPLACE([Content], N'{% if releaseRegistration &lt;= currentDate %}', N'{% if releaseRegistration <= currentDate %}')
WHERE [Id] = 554
  AND (DATALENGTH([Content]) - DATALENGTH(REPLACE([Content], N'{% if releaseRegistration &lt;= currentDate %}', N''))) / DATALENGTH(N'{% if releaseRegistration &lt;= currentDate %}') = 1
  AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId);
INSERT @log VALUES ('HtmlContent', 554, 'encoded-lte', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'HtmlContent', x.[Id], 'Content', x.[Content] FROM [HtmlContent] x WHERE x.[Id] = 557
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'HtmlContent' AND b.Id = x.[Id] AND b.Col = 'Content');
UPDATE [HtmlContent] SET [Content] = REPLACE([Content], N'{% if releaseRegistration &lt;= currentDate %}', N'{% if releaseRegistration <= currentDate %}')
WHERE [Id] = 557
  AND (DATALENGTH([Content]) - DATALENGTH(REPLACE([Content], N'{% if releaseRegistration &lt;= currentDate %}', N''))) / DATALENGTH(N'{% if releaseRegistration &lt;= currentDate %}') = 1
  AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId);
INSERT @log VALUES ('HtmlContent', 557, 'encoded-lte', @@ROWCOUNT);

INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT 'AttributeValue', x.[Id], 'Value', x.[Value] FROM [AttributeValue] x WHERE x.[Id] = 418777152 AND x.[AttributeId] = 1201 AND x.[EntityId] = 9054
  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = 'AttributeValue' AND b.Id = x.[Id] AND b.Col = 'Value');
UPDATE [AttributeValue] SET [Value] = REPLACE(REPLACE(REPLACE([Value], N'{% if row.Age == '''' or row.Age == null %}', N'{% if row.Age == null %}'), N'{% if row.Visits == '''' or row.Visits == null %}', N'{% if row.Visits == null %}'), N'{% if row.Communion == '''' or row.Communion == ''false'' or row.Communion == ''False'' or row.Communion == null %}
                                <i class="fa fa-times"></i>
                            {% else %}
                                <i class="fa fa-check"></i>
', N'{% assign communion = row.Communion | AsBoolean %}{% if communion %}
                                <i class="fa fa-check"></i>
                            {% else %}
                                <i class="fa fa-times"></i>
')
WHERE [Id] = 418777152 AND [AttributeId] = 1201 AND [EntityId] = 9054
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if row.Age == '''' or row.Age == null %}', N''))) / DATALENGTH(N'{% if row.Age == '''' or row.Age == null %}') = 1
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if row.Visits == '''' or row.Visits == null %}', N''))) / DATALENGTH(N'{% if row.Visits == '''' or row.Visits == null %}') = 1
  AND (DATALENGTH([Value]) - DATALENGTH(REPLACE([Value], N'{% if row.Communion == '''' or row.Communion == ''false'' or row.Communion == ''False'' or row.Communion == null %}
                                <i class="fa fa-times"></i>
                            {% else %}
                                <i class="fa fa-check"></i>
', N''))) / DATALENGTH(N'{% if row.Communion == '''' or row.Communion == ''false'' or row.Communion == ''False'' or row.Communion == null %}
                                <i class="fa fa-times"></i>
                            {% else %}
                                <i class="fa fa-check"></i>
') = 1;
INSERT @log VALUES ('AttributeValue', 418777152, 'int-vs-empty', @@ROWCOUNT);

UPDATE l SET [Rows] = -1 FROM @log l WHERE l.[Rows] = 0 AND NOT EXISTS (
    SELECT 1 FROM WorkflowType x WHERE l.Tbl = 'WorkflowType' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM HtmlContent x WHERE l.Tbl = 'HtmlContent' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM WorkflowActionForm x WHERE l.Tbl = 'WorkflowActionForm' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM SystemCommunication x WHERE l.Tbl = 'SystemCommunication' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM Block x WHERE l.Tbl = 'Block' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM ReportField x WHERE l.Tbl = 'ReportField' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM AttributeValue x JOIN @avkeys k ON k.Id = x.Id AND k.AttributeId = x.AttributeId AND k.EntityId = x.EntityId
        WHERE l.Tbl = 'AttributeValue' AND x.Id = l.Id);
SELECT * FROM @log ORDER BY Tbl, Id;
IF EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1)) PRINT 'WARNING: some statements did not update exactly one row - review before committing.';
IF @DryRun = 0 AND EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1))
BEGIN ROLLBACK; THROW 50000, 'ROCK9086 pass 13: a guarded update did not match exactly one row; nothing committed.', 1; END

SELECT 'ReportField' Tbl, 71196 Id, CASE WHEN CHARINDEX(N'{% if (CriminalCheckStatus == ''Approved'') or (CriminalCheckStatus == ''Reapproved'') %}' COLLATE Latin1_General_CS_AS, [Selection] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END + CASE WHEN CHARINDEX(N'{% if  Attendance1stVerifiedDate| Date:''M/d/yyyy'' | DateDiff:''Now'',''d'' > 186 %}' COLLATE Latin1_General_CS_AS, [Selection] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [ReportField] WHERE [Id] = 71196
UNION ALL
SELECT 'WorkflowType' Tbl, 72 Id, CASE WHEN CHARINDEX(N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}' COLLATE Latin1_General_CS_AS, [SummaryViewText] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [WorkflowType] WHERE [Id] = 72
UNION ALL
SELECT 'AttributeValue' Tbl, 3094280 Id, CASE WHEN CHARINDEX(N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [AttributeValue] WHERE [Id] = 3094280
UNION ALL
SELECT 'AttributeValue' Tbl, 80610811 Id, CASE WHEN CHARINDEX(N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [AttributeValue] WHERE [Id] = 80610811
UNION ALL
SELECT 'AttributeValue' Tbl, 80610821 Id, CASE WHEN CHARINDEX(N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [AttributeValue] WHERE [Id] = 80610821
UNION ALL
SELECT 'AttributeValue' Tbl, 82143392 Id, CASE WHEN CHARINDEX(N'{% if (Workflow | Attribute:''HasItOccurredBefore'') == ''True'' %}' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [AttributeValue] WHERE [Id] = 82143392
UNION ALL
SELECT 'AttributeValue' Tbl, 206537195 Id, CASE WHEN CHARINDEX(N'{% if (submitorPersonName != participantPersonName) and (minorStatus != ''Yes'') %}' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [AttributeValue] WHERE [Id] = 206537195
UNION ALL
SELECT 'AttributeValue' Tbl, 449129641 Id, CASE WHEN CHARINDEX(N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [AttributeValue] WHERE [Id] = 449129641
UNION ALL
SELECT 'AttributeValue' Tbl, 449130783 Id, CASE WHEN CHARINDEX(N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [AttributeValue] WHERE [Id] = 449130783
UNION ALL
SELECT 'AttributeValue' Tbl, 449130791 Id, CASE WHEN CHARINDEX(N'{% if Workflow | Attribute:''CardReopened'' == ''Yes'' %}' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [AttributeValue] WHERE [Id] = 449130791
UNION ALL
SELECT 'HtmlContent' Tbl, 546 Id, CASE WHEN CHARINDEX(N'{% if registrationClosed &lt;= currentDate %}' COLLATE Latin1_General_CS_AS, [Content] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [HtmlContent] WHERE [Id] = 546
UNION ALL
SELECT 'HtmlContent' Tbl, 547 Id, CASE WHEN CHARINDEX(N'{% if releaseRegistration &lt;= currentDate %}' COLLATE Latin1_General_CS_AS, [Content] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [HtmlContent] WHERE [Id] = 547
UNION ALL
SELECT 'HtmlContent' Tbl, 548 Id, CASE WHEN CHARINDEX(N'{% if releaseRegistration &lt;= currentDate %}' COLLATE Latin1_General_CS_AS, [Content] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [HtmlContent] WHERE [Id] = 548
UNION ALL
SELECT 'HtmlContent' Tbl, 550 Id, CASE WHEN CHARINDEX(N'{% if releaseRegistration &lt;= currentDate %}' COLLATE Latin1_General_CS_AS, [Content] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [HtmlContent] WHERE [Id] = 550
UNION ALL
SELECT 'HtmlContent' Tbl, 554 Id, CASE WHEN CHARINDEX(N'{% if releaseRegistration &lt;= currentDate %}' COLLATE Latin1_General_CS_AS, [Content] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [HtmlContent] WHERE [Id] = 554
UNION ALL
SELECT 'HtmlContent' Tbl, 557 Id, CASE WHEN CHARINDEX(N'{% if releaseRegistration &lt;= currentDate %}' COLLATE Latin1_General_CS_AS, [Content] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [HtmlContent] WHERE [Id] = 557
UNION ALL
SELECT 'AttributeValue' Tbl, 418777152 Id, CASE WHEN CHARINDEX(N'{% if row.Age == '''' or row.Age == null %}' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END + CASE WHEN CHARINDEX(N'{% if row.Visits == '''' or row.Visits == null %}' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END + CASE WHEN CHARINDEX(N'{% if row.Communion == '''' or row.Communion == ''false'' or row.Communion == ''False'' or row.Communion == null %}
                                <i class="fa fa-times"></i>
                            {% else %}
                                <i class="fa fa-check"></i>
' COLLATE Latin1_General_CS_AS, [Value] COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END StillOld FROM [AttributeValue] WHERE [Id] = 418777152;

IF @DryRun = 1 BEGIN ROLLBACK; PRINT 'Dry run - rolled back.'; END ELSE BEGIN COMMIT; PRINT 'Committed. Now clear the Rock cache.'; END
