"""ROCK-9086 pass 12b: CommunicationTemplate 4 (held out of 016 until the owner chose, 2026-09-30).
Reads vals/p15-<Table>-<Id>[-<Col>].txt (exact prod values), applies literal (old, new) rules, and writes
017_apply_commtemplate4.sql with per-row guarded REPLACEs (same shape as 014/015)."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
V = os.environ.get("ROCK9086_VALS", os.path.join(HERE, "vals"))  # prod dumps are not committed; point ROCK9086_VALS at them
OUT = os.path.join(HERE, "017_apply_commtemplate4.sql")

# Neighborhood Group - Recommit Final Reminder: an editor URL-encoded the spaces inside {{ }}. Fluid cannot parse the
# template at all; DotLiquid renders an empty key. The link goes to Webflow (www.southeastchristian.org -> www.se.church),
# so a Rock login token must not go there: drop the tag, which is what DotLiquid sends today (LavaProbe U1).
R_RCKIPID = [("rckipid={{%20Person.UrlEncodedKey%20}}", "rckipid=")]

# (table, id, column, dump name, fix-rule label, rules)
ROWS = [
    ("CommunicationTemplate", 4, "Message", "p15-CT-4", "urlencoded-mustache", R_RCKIPID),
]

# AttributeValue Id -> (AttributeId, EntityId) on production; ids are not the same row on every database
AV_KEYS = {0: (0, 0)}  # no AttributeValue rows; keeps the @avkeys insert valid

def q(s):
    assert all(ord(c) < 128 for c in s), s
    return "N'" + s.replace("'", "''") + "'"

def cnt(col, o):
    # DATALENGTH, not LEN: LEN drops trailing spaces
    return "(DATALENGTH(%s) - DATALENGTH(REPLACE(%s, %s, N''))) / DATALENGTH(%s)" % (col, col, q(o), q(o))

L = ["""-- ROCK9086 pass 12b (generated by gen_017.py): CommunicationTemplate 4 "Neighborhood Group - Recommit Final Reminder".
-- `rckipid={{%20Person.UrlEncodedKey%20}}` is a Fluid parse error (the whole email fails); DotLiquid renders the key empty.
-- The link points at Webflow, so no Rock login token: the tag is removed and the output matches DotLiquid today.
-- Same guarded shape as 014-016. Clear the Rock cache after.
SET NOCOUNT ON; SET XACT_ABORT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
DECLARE @DryRun bit = 1;
DECLARE @log TABLE (Tbl sysname, Id int, FixRule varchar(40), [Rows] int);
DECLARE @avkeys TABLE (Id int, AttributeId int, EntityId int);
INSERT @avkeys VALUES """ + ", ".join("(%d, %d, %d)" % (k, v[0], v[1]) for k, v in sorted(AV_KEYS.items())) + """;
BEGIN TRAN;

IF OBJECT_ID('dbo._ROCK9086_LavaBackup') IS NULL
    CREATE TABLE dbo._ROCK9086_LavaBackup (Tbl sysname NOT NULL, Id int NOT NULL, Col sysname NOT NULL, OldValue nvarchar(max) NULL, BackedUpAt datetime NOT NULL DEFAULT GETDATE());
"""]
verify = []
for tbl, i, col, dump, label, rules in ROWS:
    t = open(os.path.join(V, dump + ".txt"), encoding="utf-8", newline="").read()
    pairs = []
    for o, n in rules:
        c = t.count(o)
        if c:
            pairs.append((o, n, c))
    assert len(pairs) == len(rules), (tbl, i, "a rule did not match", [o for o, n in rules if o not in t])
    new = t
    for o, n, c in pairs:
        new = new.replace(o, n)
    for o, n, c in pairs:
        assert o not in new or o in n, (tbl, i, o)
    colq = "[%s]" % col
    # one backup per row, holding the original value; AttributeValue also matches AttributeId/EntityId
    key = " AND x.[AttributeId] = %d AND x.[EntityId] = %d" % AV_KEYS[i] if tbl == "AttributeValue" else ""
    L.append("INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT '%s', x.[Id], '%s', x.%s FROM [%s] x WHERE x.[Id] = %d%s\n"
             "  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = '%s' AND b.Id = x.[Id] AND b.Col = '%s');"
             % (tbl, col, colq, tbl, i, key, tbl, col))
    expr = colq
    for o, n, c in pairs:
        expr = "REPLACE(%s, %s, %s)" % (expr, q(o), q(n))
    conds = ["[Id] = %d" % i] + ["%s = %d" % (cnt(colq, o), c) for o, n, c in pairs]
    if tbl == "AttributeValue":
        conds[0] += " AND [AttributeId] = %d AND [EntityId] = %d" % AV_KEYS[i]
    if tbl == "HtmlContent":
        conds.append("[Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId)")
    L.append("UPDATE [%s] SET %s = %s\nWHERE %s;" % (tbl, colq, expr, "\n  AND ".join(conds)))
    L.append("INSERT @log VALUES ('%s', %d, '%s', @@ROWCOUNT);\n" % (tbl, i, label))
    still = " + ".join("CASE WHEN CHARINDEX(%s COLLATE Latin1_General_CS_AS, %s COLLATE Latin1_General_CS_AS) > 0 THEN 1 ELSE 0 END"
                       % (q(o), colq) for o, n, c in pairs if o not in n)
    verify.append("SELECT '%s' Tbl, %d Id, %s StillOld FROM [%s] WHERE [Id] = %d" % (tbl, i, still or "0", tbl, i))
    for o, n, c in pairs:
        print("%-19s %9d %-15s x%d  %s  ->  %s" % (tbl, i, col, c, o[:60].replace("\n", " "), n[:60].replace("\n", " ")))

L.append("""UPDATE l SET [Rows] = -1 FROM @log l WHERE l.[Rows] = 0 AND NOT EXISTS (
    SELECT 1 FROM WorkflowType x WHERE l.Tbl = 'WorkflowType' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM HtmlContent x WHERE l.Tbl = 'HtmlContent' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM WorkflowActionForm x WHERE l.Tbl = 'WorkflowActionForm' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM SystemCommunication x WHERE l.Tbl = 'SystemCommunication' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM Block x WHERE l.Tbl = 'Block' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM CommunicationTemplate x WHERE l.Tbl = 'CommunicationTemplate' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM ReportField x WHERE l.Tbl = 'ReportField' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM AttributeValue x JOIN @avkeys k ON k.Id = x.Id AND k.AttributeId = x.AttributeId AND k.EntityId = x.EntityId
        WHERE l.Tbl = 'AttributeValue' AND x.Id = l.Id);
SELECT * FROM @log ORDER BY Tbl, Id;
IF EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1)) PRINT 'WARNING: some statements did not update exactly one row - review before committing.';
IF @DryRun = 0 AND EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1))
BEGIN ROLLBACK; THROW 50000, 'ROCK9086 pass 12b: a guarded update did not match exactly one row; nothing committed.', 1; END
""")
L.append("\nUNION ALL\n".join(verify) + ";\n")
L.append("IF @DryRun = 1 BEGIN ROLLBACK; PRINT 'Dry run - rolled back.'; END ELSE BEGIN COMMIT; PRINT 'Committed. Now clear the Rock cache.'; END\n")
open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
print("rows:", len(ROWS), "->", OUT)
