"""Generate Tools/LavaFluidMigration/ROCK-9086/010_apply_prodpass3.sql from the dumped prod values in scratchpad/vals.
Every (old, new) pair is checked against the dumped value first: it must occur the expected number of times."""
import os, sys
V = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vals")
OUT = r"C:\Users\stephenl\source\repos\RockPlugins-16\Tools\LavaFluidMigration\ROCK-9086\010_apply_prodpass3.sql"
BSQ = "{%- capture bsq -%}\\\"{%- endcapture -%}"          # {%- capture bsq -%}\"{%- endcapture -%}

def val(name):
    return open(os.path.join(V, name + ".txt"), encoding="utf-8").read()

def q(s):   # T-SQL N'' literal
    assert all(ord(c) < 128 for c in s), s
    return "N'" + s.replace("'", "''") + "'"

rows = []   # (tbl, idcol, id, col, fixrule, [(old, new, expected_count)], prepend, extra_where)
rf_ids = sorted(int(f[3:-4]) for f in os.listdir(V) if f.startswith("rf-"))
for i in rf_ids:
    rows.append(("ReportField", i, "Selection", "rindex-comma", [("forloop.rindex > 1", "forloop.last == false", 1)], None, ""))
rows.append(("HtmlContent", 12894, "Content", "bool-vs-rawvalue",
             [("{%- if hideTitle == false -%}", "{%- if hideTitle == 'False' -%}", 1),
              ("{% if roundHeaderImage == true %}", "{% if roundHeaderImage == 'True' %}", 1)], None,
             " AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = 6700)"))
for i in (47, 724, 732, 733, 734):
    rows.append(("WorkflowType", i, "NoActionMessage", "bool-vs-string",
                 [("{% if completed == 'true' %}", "{% if completed %}", 1), ("{% elseif completed == 'false' %}", "{% else %}", 1)], None, ""))
MUST = [("{% assign EventContact = {{Workflow | Attribute:'StaffContactPerson', 'Object'}} %}", "{% assign EventContact = Workflow | Attribute:'StaffContactPerson', 'Object' %}"),
        ("{% assign Initiator = {{Workflow | Attribute:'EventInitiator', 'Object'}} %}", "{% assign Initiator = Workflow | Attribute:'EventInitiator', 'Object' %}"),
        ("{% assign ChildcareContact = {{Workflow | Attribute:'ChildcareContactPerson', 'Object'}} %}", "{% assign ChildcareContact = Workflow | Attribute:'ChildcareContactPerson', 'Object' %}")]
for i in (119518134, 119518144, 165745851, 175793856, 181933899):
    t = val("av-%d" % i)
    pairs = [(o, n, t.count(o)) for o, n in MUST if t.count(o)]
    rows.append(("AttributeValue", i, "Value", "mustache-in-assign", pairs, None, ""))
for i in (145692343, 328460478, 340611135):
    t = val("av-%d" % i)
    pairs = []
    for fld in ("Name", "Title", "CampusName", "MeetingLocation", "CustomSchedule"):
        o = '"%s": "{{g.%s}}"' % (fld, fld)
        if t.count(o):
            pairs.append((o, '"%s": "{{g.%s | Replace:\'"\',bsq}}"' % (fld, fld), t.count(o)))
    assert "bsq" not in t
    rows.append(("AttributeValue", i, "Value", "json-escape", pairs, BSQ, ""))
rows.append(("AttributeValue", 449094742, "Value", "regex-backref-capture",
             [("{%- assign same = d | RegExMatch:'^([0-9])\\1\\1\\1\\1\\1\\1\\1\\1\\1$' -%}",
               "{%- capture reSame -%}^([0-9])\\1\\1\\1\\1\\1\\1\\1\\1\\1${%- endcapture -%}{%- assign same = d | RegExMatch:reSame -%}", 1)], None, ""))

# verify against the dumped values
dump = {"ReportField": "rf", "HtmlContent": "hc", "WorkflowType": "wt", "AttributeValue": "av"}
bad = 0
for tbl, i, col, rule, pairs, pre, extra in rows:
    t = val("%s-%d" % (dump[tbl], i))
    for o, n, c in pairs:
        if t.count(o) != c or c < 1:
            print("MISMATCH", tbl, i, repr(o), t.count(o), c); bad += 1
    if not pairs:
        print("NO PAIRS", tbl, i); bad += 1
if bad:
    sys.exit(1)

idcol = "Id"
L = []
L.append("""-- ROCK9086 pass 7: rows production reported under Fluid verification on 2026-09-25 after 009 (14:45-16:05).
-- Generated by gen_010.py from the live prod values; every REPLACE was checked against them before writing this file.
-- Same shape as 005-009: guarded REPLACE per row, @DryRun = 1 rolls back, live run is all-or-nothing, backups to
-- dbo._ROCK9086_LavaBackup, rows absent from the target database log -1. Clear the Rock cache afterwards.
--
-- Rows                                           Pattern                                            Fluid today / fix
-- ReportField x%d (family "Children:/Parents:"    {%% if forloop.rindex > 1 %%},{%% endif %%}               Fluid 2.3.1 numbers rindex backwards: the comma
--   Lava fields in 25 staff/family reports)                                                          lands on the wrong items -> forloop.last == false
-- HtmlContent 12894 (block 6700, /links/{slug})  hideTitle == false, roundHeaderImage == true       RawValue is the string 'True'/'False'; Fluid
--                                                 against Attribute ... 'RawValue'                   never matches -> heading hidden; compare strings
-- WorkflowType 47, 724, 732, 733, 734             {%% assign completed = false %%} ... == 'false'       bool vs string: Fluid matches neither branch ->
--   NoActionMessage (volunteer / church reference)                                                   message blank; {%% if completed %%} / {%% else %%}
-- AttributeValue x5 (workflow 639 email bodies)   {%% assign X = {{Workflow | Attribute:...}} %%}      "A value was expected" -> bare expression
-- AttributeValue 145692343, 328460478, 340611135  "Name": "{{g.Name}}" etc. unescaped in JSON       a group name with a " breaks webrequest on
--   (publishgroup/list, /v2, /aigroupfinder)                                                         Fluid -> Replace:'"',bsq (same fix as 006)
-- AttributeValue 449094742 (RSVP Weekend (FINAL)) RegExMatch:'^([0-9])\\1\\1...'                      \\1 escape in a quoted string -> capture
-- Every rewrite verified identical on both engines with LavaProbe (F1, F2, H*, G1-G4, J4, F7).
SET NOCOUNT ON; SET XACT_ABORT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
DECLARE @DryRun bit = 1;
DECLARE @log TABLE (Tbl sysname, Id int, FixRule varchar(40), [Rows] int);
BEGIN TRAN;

IF OBJECT_ID('dbo._ROCK9086_LavaBackup') IS NULL
    CREATE TABLE dbo._ROCK9086_LavaBackup (Tbl sysname NOT NULL, Id int NOT NULL, Col sysname NOT NULL, OldValue nvarchar(max) NULL, BackedUpAt datetime NOT NULL DEFAULT GETDATE());
""" % len(rf_ids))
for tbl, col in (("ReportField", "Selection"), ("HtmlContent", "Content"), ("WorkflowType", "NoActionMessage"), ("AttributeValue", "Value")):
    ids = [str(r[1]) for r in rows if r[0] == tbl]
    L.append("INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT '%s', x.[Id], '%s', x.[%s] FROM %s x WHERE x.[Id] IN (%s)\n"
             "  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = '%s' AND b.Id = x.[Id]);" % (tbl, col, col, tbl, ", ".join(ids), tbl))
L.append("")
for tbl, i, col, rule, pairs, pre, extra in rows:
    expr = "[%s]" % col
    for o, n, c in pairs:
        expr = "REPLACE(%s, %s, %s)" % (expr, q(o), q(n))
    if pre:
        expr = "%s + %s" % (q(pre), expr)
    conds = ["[Id] = %d" % i]
    for o, n, c in pairs:
        conds.append("(LEN([%s]) - LEN(REPLACE([%s], %s, N''))) / LEN(%s) = %d" % (col, col, q(o), q(o), c))
    if pre:
        conds.append("CHARINDEX(N'capture bsq', [%s]) = 0" % col)
    L.append("UPDATE %s SET [%s] = %s\nWHERE %s%s;" % (tbl, col, expr, "\n  AND ".join(conds), extra))
    L.append("INSERT @log VALUES ('%s', %d, '%s', @@ROWCOUNT);" % (tbl, i, rule))
L.append("""
UPDATE l SET [Rows] = -1 FROM @log l WHERE l.[Rows] = 0 AND NOT EXISTS (
    SELECT 1 FROM ReportField x WHERE l.Tbl = 'ReportField' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM HtmlContent x WHERE l.Tbl = 'HtmlContent' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM WorkflowType x WHERE l.Tbl = 'WorkflowType' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM AttributeValue x WHERE l.Tbl = 'AttributeValue' AND x.Id = l.Id);

SELECT Tbl, COUNT(*) Stmts, SUM(CASE WHEN [Rows] = 1 THEN 1 ELSE 0 END) Updated, SUM(CASE WHEN [Rows] = -1 THEN 1 ELSE 0 END) Absent,
       SUM(CASE WHEN [Rows] NOT IN (1, -1) THEN 1 ELSE 0 END) Problems FROM @log GROUP BY Tbl;
SELECT * FROM @log WHERE [Rows] <> 1 ORDER BY Tbl, Id;
IF EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1)) PRINT 'WARNING: some statements did not update exactly one row - review before committing.';
IF @DryRun = 0 AND EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1))
BEGIN ROLLBACK; THROW 50000, 'ROCK9086 pass 7: a guarded update did not match exactly one row; nothing committed.', 1; END

-- verify: none of the old forms remain
SELECT 'ReportField' Tbl, COUNT(*) StillOld FROM ReportField WHERE Selection LIKE '%forloop.rindex > 1%'
UNION ALL SELECT 'HtmlContent', COUNT(*) FROM HtmlContent WHERE Id = 12894 AND (Content LIKE '%hideTitle == false%' OR Content LIKE '%roundHeaderImage == true %')
UNION ALL SELECT 'WorkflowType', COUNT(*) FROM WorkflowType WHERE Id IN (47, 724, 732, 733, 734) AND NoActionMessage LIKE '%completed == ''false''%'
UNION ALL SELECT 'AttributeValue', COUNT(*) FROM AttributeValue WHERE Id IN (119518134, 119518144, 165745851, 175793856, 181933899, 145692343, 328460478, 340611135, 449094742)
    AND (Value LIKE '%= {{Workflow |%' OR Value LIKE '%"Name": "{{g.Name}}"%' OR Value LIKE '%"Title": "{{g.Title}}"%' OR Value LIKE '%RegExMatch:''^([[]0-9])%');

IF @DryRun = 1 BEGIN ROLLBACK; PRINT 'Dry run - rolled back.'; END ELSE BEGIN COMMIT; PRINT 'Committed. Now clear the Rock cache.'; END
""")
open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
print("wrote", OUT, "rows:", len(rows))
