"""Generate Tools/LavaFluidMigration/ROCK-9086/012_apply_prodpass4.sql from the dumped prod values in scratchpad/vals,
plus probe-cases22.txt (LavaProbe cases comparing each old template on DotLiquid with the new one on both engines)."""
import os, re, sys, hashlib
HERE = os.path.dirname(os.path.abspath(__file__))
V = os.path.join(HERE, "vals")
OUT = r"C:\Users\stephenl\source\repos\RockPlugins-16\Tools\LavaFluidMigration\ROCK-9086\012_apply_prodpass4.sql"

def val(n): return open(os.path.join(V, n + ".txt"), encoding="utf-8", newline="").read()

def q(s):
    """T-SQL N'' literal; non-ASCII characters become NCHAR(n) pieces."""
    parts, buf = [], []
    for ch in s:
        if ord(ch) < 128:
            buf.append(ch)
        else:
            if buf: parts.append("N'" + "".join(buf).replace("'", "''") + "'"); buf = []
            parts.append("NCHAR(%d)" % ord(ch))
    if buf or not parts: parts.append("N'" + "".join(buf).replace("'", "''") + "'")
    return parts[0] if len(parts) == 1 else "CAST(" + " + ".join(parts) + " AS nvarchar(max))"

def flatten_nested_comments(t):
    """Keep outermost comment/endcomment tags, drop the inner ones (Fluid ends a comment at the first endcomment)."""
    out, depth, pos = [], 0, 0
    for m in re.finditer(r"\{%-?\s*(end)?comment\s*-?%\}", t):
        out.append(t[pos:m.start()]); pos = m.end()
        if m.group(1):
            depth -= 1
            if depth == 0: out.append(m.group(0))
        else:
            if depth == 0: out.append(m.group(0))
            depth += 1
        assert depth >= 0
    assert depth == 0
    out.append(t[pos:])
    return "".join(out)

rows = []   # (tbl, col, id, rule, kind, payload)
# 1. college-age nested comments: whole-value set, guarded by hash of the exact current value
old = val("n-hc-10753"); new = flatten_nested_comments(old)
rows.append(("HtmlContent", "Content", 10753, "nested-comment", "set", (old, new)))
# 2. community engagement: parens + rindex0 in if (DotLiquid only ever hit the last-item branch)
o = "{% if (forloop.rindex0 == 0 %}<br />{% break %}{% elseif (forloop.rindex0 == 1 and timesCount > 2) %} &amp;{% else %},{% endif %}"
n = "{% if forloop.last %}<br />{% break %}{% else %},{% endif %}"
rows.append(("HtmlContent", "Content", 10536, "parens-rindex0", "replace", [(o, n, 1)]))
# 3. Workflow Form Notification: editor-mangled link -> stock Rock line
o = "<a href='{{ ' global'=\"\" |=\"\" attribute:'internalapplicationroot'=\"\" }}workflowentry/{{=\"\" workflow.workflowtypeid=\"\" }}?workflowguid=\"{{\" workflow.guid=\"\" }}'=\"\">"
n = "<a href='{{ 'Global' | Attribute:'InternalApplicationRoot' }}WorkflowEntry/{{ Workflow.WorkflowTypeId }}?WorkflowGuid={{ Workflow.Guid }}'>"
rows.append(("SystemCommunication", "Body", 9, "mangled-href", "replace", [(o, n, 1)]))
# 4. reference PDFs: text compared to 0 -> its Size
for i in (419773844, 25012462):
    pairs = [("{%% assign textSize = Workflow | Attribute:'%s' %%}" % k, "{%% assign textSize = Workflow | Attribute:'%s' | Size %%}" % k, 1)
             for k in ("ReasontheyShouldNOTVolunteerText", "AnythingElseText")]
    rows.append(("AttributeValue", "Value", i, "text-vs-zero", "replace", pairs))
# 5. Baptisms report: uppercase AND and parens
tags = ["{% if MaxDateRange != empty AND MinDateRange != empty  %}", "{% if MinDateRange != empty AND MaxDateRange == empty%}",
        "{% if MaxDateRange != empty AND MinDateRange == empty%}", "{% elseif (MinAgeRange != empty AND MaxAgeRange != empty) %}",
        "{% elseif (MinAgeRange != empty AND MaxAgeRange == empty) %}", "{% elseif (MinAgeRange == empty AND MaxAgeRange != empty) %}"]
pairs = [(t_, t_.replace(" AND ", " and ").replace("{% elseif (", "{% elseif ").replace(") %}", " %}"), 1) for t_ in tags]
rows.append(("AttributeValue", "Value", 199751449, "upper-AND-parens", "replace", pairs))

dump = {("HtmlContent", 10753): "n-hc-10753", ("HtmlContent", 10536): "n-hc-10536", ("SystemCommunication", 9): "n-sc-9",
        ("AttributeValue", 419773844): "n-av-419773844", ("AttributeValue", 25012462): "n-av-25012462", ("AttributeValue", 199751449): "n-av-199751449"}
bad = 0
for tbl, col, i, rule, kind, p in rows:
    if kind == "replace":
        t = val(dump[(tbl, i)])
        for o, n, c in p:
            if t.count(o) != c: print("MISMATCH", tbl, i, repr(o), t.count(o)); bad += 1
if bad: sys.exit(1)

L = ["""-- ROCK9086 pass 9: rows production reported under Fluid verification 16:45-20:10 on 2026-09-25 (after 010/011).
-- Generated by gen_012.py from the live prod values; every REPLACE was checked against them before writing this file.
-- Same shape as 005-011: guarded update per row, @DryRun = 1 rolls back, live run is all-or-nothing, backups to
-- dbo._ROCK9086_LavaBackup, rows absent from the target database log -1. Clear the Rock cache afterwards.
--
-- HtmlContent 10753 (/ministries/college-age)   nested {% comment %}: Fluid ends at the first endcomment -> "Unknown tag
--                                                'endcomment'". Inner comment tags dropped, outer kept (whole value set,
--                                                guarded by the SHA-256 of the exact current value).
-- HtmlContent 10536 (/communityengagement)       {% if (forloop.rindex0 == 0 %} - parens + Fluid's reversed rindex0.
--                                                DotLiquid only ever took the last-item branch -> {% if forloop.last %}.
-- SystemCommunication 9 (Workflow Form           the link was mangled by an HTML editor on 2020-11-20
-- Notification)                                  ({{ ' global'="" |="" ...) -> Fluid parse error; restored to the stock line.
--                                                BEHAVIOUR CHANGE: the "requires action" link works again on both engines.
-- AttributeValue 419773844, 25012462             {% assign textSize = Workflow | Attribute:'...Text' %}{% if textSize > 0 %}
-- (reference "Create the PDF")                   compares text to 0: DotLiquid true when non-empty, Fluid never -> | Size.
-- AttributeValue 199751449 (page 3040            uppercase AND (DotLiquid ignores everything after it) and parens in elseif.
-- Baptisms By Campus, Date & Age)                BEHAVIOUR CHANGE: the age filter now works as written; on DotLiquid it
--                                                emitted `age <= CAST('' AS INT)` whenever MaxAgeRange was blank.
-- Verified with LavaProbe (M1-M3, gen_cases21 matrix, probe-cases22).
SET NOCOUNT ON; SET XACT_ABORT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
DECLARE @DryRun bit = 1;
DECLARE @log TABLE (Tbl sysname, Id int, FixRule varchar(40), [Rows] int);
BEGIN TRAN;

IF OBJECT_ID('dbo._ROCK9086_LavaBackup') IS NULL
    CREATE TABLE dbo._ROCK9086_LavaBackup (Tbl sysname NOT NULL, Id int NOT NULL, Col sysname NOT NULL, OldValue nvarchar(max) NULL, BackedUpAt datetime NOT NULL DEFAULT GETDATE());
"""]
for tbl, col in sorted(set((r[0], r[1]) for r in rows)):
    ids = sorted(set(str(r[2]) for r in rows if r[0] == tbl))
    L.append("INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT '%s', x.[Id], '%s', x.[%s] FROM %s x WHERE x.[Id] IN (%s)\n"
             "  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = '%s' AND b.Id = x.[Id] AND b.Col = '%s');"
             % (tbl, col, col, tbl, ", ".join(ids), tbl, col))
L.append("")
for tbl, col, i, rule, kind, p in rows:
    extra = " AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId)" if tbl == "HtmlContent" else ""
    if kind == "set":
        old, new = p
        h = hashlib.sha256(old.encode("utf-16-le")).hexdigest().upper()
        L.append("UPDATE %s SET [%s] = %s\nWHERE [Id] = %d AND HASHBYTES('SHA2_256', [%s]) = 0x%s%s;" % (tbl, col, q(new), i, col, h, extra))
    else:
        expr = "[%s]" % col
        for o, n, c in p: expr = "REPLACE(%s, %s, %s)" % (expr, q(o), q(n))
        conds = ["[Id] = %d" % i] + ["(LEN([%s]) - LEN(REPLACE([%s], %s, N''))) / LEN(%s) = %d" % (col, col, q(o), q(o), c) for o, n, c in p]
        L.append("UPDATE %s SET [%s] = %s\nWHERE %s%s;" % (tbl, col, expr, "\n  AND ".join(conds), extra))
    L.append("INSERT @log VALUES ('%s', %d, '%s', @@ROWCOUNT);" % (tbl, i, rule))
L.append("""
UPDATE l SET [Rows] = -1 FROM @log l WHERE l.[Rows] = 0 AND NOT EXISTS (
    SELECT 1 FROM AttributeValue x WHERE l.Tbl = 'AttributeValue' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM HtmlContent x WHERE l.Tbl = 'HtmlContent' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM SystemCommunication x WHERE l.Tbl = 'SystemCommunication' AND x.Id = l.Id);

SELECT * FROM @log ORDER BY Tbl, Id;
IF EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1)) PRINT 'WARNING: some statements did not update exactly one row - review before committing.';
IF @DryRun = 0 AND EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1))
BEGIN ROLLBACK; THROW 50000, 'ROCK9086 pass 9: a guarded update did not match exactly one row; nothing committed.', 1; END

SELECT 'StillOld' Chk,
  (SELECT COUNT(*) FROM HtmlContent WHERE Id = 10536 AND Content LIKE '%{[%] if (forloop.rindex0%') Html10536,
  (SELECT COUNT(*) FROM SystemCommunication WHERE Id = 9 AND Body LIKE '%'' global''=""%') SysComm9,
  (SELECT COUNT(*) FROM AttributeValue WHERE Id IN (419773844, 25012462) AND Value LIKE '%Text'' [%]}{[%] if textSize > 0%') RefPdf,
  (SELECT COUNT(*) FROM AttributeValue WHERE Id = 199751449 AND Value COLLATE Latin1_General_CS_AS LIKE '%empty AND %') Bap3040,
  (SELECT (LEN(Content) - LEN(REPLACE(Content, N'endcomment', N''))) / 10 FROM HtmlContent WHERE Id = 10753) EndCommentsIn10753;

IF @DryRun = 1 BEGIN ROLLBACK; PRINT 'Dry run - rolled back.'; END ELSE BEGIN COMMIT; PRINT 'Committed. Now clear the Rock cache.'; END
""")
open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))

# probe cases: each old template on DotLiquid vs the new template on both
cases = []
def add(name, old_t, new_t):
    cases.append("### %s-OLD\n%s" % (name, old_t)); cases.append("### %s-NEW\n%s" % (name, new_t))
add("P1-college", val("n-hc-10753"), flatten_nested_comments(val("n-hc-10753")))
loop = "{% assign serviceDay = '' %}{% assign timesCount = 3 %}{% assign ts = '9:00,10:30,12:00' | Split:',' %}{%- for times in ts -%} {{times}}%s{%- endfor -%}"
add("P2-times", loop.replace("%s", rows[1][5][0][0]), loop.replace("%s", rows[1][5][0][1]))
sc = "{% assign w = 'x' %}<p>Req: " + "%s" + "{{ Workflow.Name }}</a></p>"
add("P3-sc9", sc.replace("%s", rows[2][5][0][0]), sc.replace("%s", rows[2][5][0][1]))
open(os.path.join(HERE, "probe-cases22.txt"), "w", encoding="utf-8").write("\n".join(cases) + "\n")
print("wrote", OUT, "rows:", len(rows))
print("10753 comment tags old/new:", len(re.findall(r"\{%-?\s*(?:end)?comment\s*-?%\}", old)), len(re.findall(r"\{%-?\s*(?:end)?comment\s*-?%\}", new)))
