"""Generate Tools/LavaFluidMigration/ROCK-9086/011_apply_assign_mustache.sql from the dumped prod values in scratchpad/vals.
Rewrites `{% assign X = {{EXPR}} %}` (no space inside the braces - the form DotLiquid resolves) to `{% assign X = EXPR %}`.
Every rewrite is checked against the dumped value first."""
import os, re, sys
V = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vals")
OUT = r"C:\Users\stephenl\source\repos\RockPlugins-16\Tools\LavaFluidMigration\ROCK-9086\011_apply_assign_mustache.sql"
TIGHT = re.compile(r"\{% assign ([A-Za-z_]\w*) = \{\{([^{}\s][^{}]*[^{}\s])\}\} %\}")
SKIP = {"sw-121667807"}   # a whole template inside one assign tag - fails to parse on DotLiquid too; left for the owner
TABLES = {"sw": ("AttributeValue", "Value"), "fh": ("WorkflowActionForm", "Header"), "ht": ("HtmlContent", "Content")}

def q(s):
    assert all(ord(c) < 128 for c in s), s
    return "N'" + s.replace("'", "''") + "'"

rows = []
for f in sorted(os.listdir(V)):
    pre, _, rest = f.partition("-")
    name = f[:-4]
    if pre not in TABLES or name in SKIP:
        continue
    t = open(os.path.join(V, f), encoding="utf-8").read()
    tags = sorted(set(m.group(0) for m in TIGHT.finditer(t)))
    if not tags:
        continue
    pairs = []
    for tg in tags:
        m = TIGHT.fullmatch(tg)
        new = "{%% assign %s = %s %%}" % (m.group(1), m.group(2))
        pairs.append((tg, new, t.count(tg)))
    tbl, col = TABLES[pre]
    rows.append((tbl, col, int(rest[:-4]), pairs))

L = ["""-- ROCK9086 pass 8: `{% assign X = {{EXPR}} %}` - a {{ }} inside an assign, the class 008 fixed on the View Case page.
-- Generated by gen_011.py from the live prod values (2026-09-25). Fluid rejects it ("A value was expected"); DotLiquid
-- resolves the no-space form, so the bare expression renders the same on both engines (LavaProbe G1-G3, V1/V2).
-- A wide LIKE first suggested 273 workflow rows; the precise scan found __NROWS__ rows (the rest were an assign and a later
-- `= {{ }}` in SQL text). Left alone: AttributeValue 121667807 (workflow 639 "Set Today's date"), which packs a whole
-- template inside one assign tag and fails to parse on DotLiquid as well.
-- Same shape as 005-010: guarded REPLACE per row, @DryRun = 1 rolls back, live run is all-or-nothing, backups to
-- dbo._ROCK9086_LavaBackup, rows absent from the target database log -1. Clear the Rock cache afterwards.
SET NOCOUNT ON; SET XACT_ABORT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
DECLARE @DryRun bit = 1;
DECLARE @log TABLE (Tbl sysname, Id int, FixRule varchar(40), [Rows] int);
BEGIN TRAN;

IF OBJECT_ID('dbo._ROCK9086_LavaBackup') IS NULL
    CREATE TABLE dbo._ROCK9086_LavaBackup (Tbl sysname NOT NULL, Id int NOT NULL, Col sysname NOT NULL, OldValue nvarchar(max) NULL, BackedUpAt datetime NOT NULL DEFAULT GETDATE());
""".replace("__NROWS__", str(len(rows)))]
for tbl, col in sorted(set((r[0], r[1]) for r in rows)):
    ids = [str(r[2]) for r in rows if r[0] == tbl]
    L.append("INSERT dbo._ROCK9086_LavaBackup (Tbl, Id, Col, OldValue) SELECT '%s', x.[Id], '%s', x.[%s] FROM %s x WHERE x.[Id] IN (%s)\n"
             "  AND NOT EXISTS (SELECT 1 FROM dbo._ROCK9086_LavaBackup b WHERE b.Tbl = '%s' AND b.Id = x.[Id] AND b.Col = '%s');"
             % (tbl, col, col, tbl, ", ".join(ids), tbl, col))
L.append("")
for tbl, col, i, pairs in rows:
    expr = "[%s]" % col
    for o, n, c in pairs:
        expr = "REPLACE(%s, %s, %s)" % (expr, q(o), q(n))
    conds = ["[Id] = %d" % i] + ["(LEN([%s]) - LEN(REPLACE([%s], %s, N''))) / LEN(%s) = %d" % (col, col, q(o), q(o), c) for o, n, c in pairs]
    extra = " AND [Version] = (SELECT MAX([Version]) FROM HtmlContent h2 WHERE h2.BlockId = HtmlContent.BlockId)" if tbl == "HtmlContent" else ""
    L.append("UPDATE %s SET [%s] = %s\nWHERE %s%s;" % (tbl, col, expr, "\n  AND ".join(conds), extra))
    L.append("INSERT @log VALUES ('%s', %d, 'mustache-in-assign', @@ROWCOUNT);" % (tbl, i))
L.append("""
UPDATE l SET [Rows] = -1 FROM @log l WHERE l.[Rows] = 0 AND NOT EXISTS (
    SELECT 1 FROM AttributeValue x WHERE l.Tbl = 'AttributeValue' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM WorkflowActionForm x WHERE l.Tbl = 'WorkflowActionForm' AND x.Id = l.Id UNION ALL
    SELECT 1 FROM HtmlContent x WHERE l.Tbl = 'HtmlContent' AND x.Id = l.Id);

SELECT Tbl, COUNT(*) Stmts, SUM(CASE WHEN [Rows] = 1 THEN 1 ELSE 0 END) Updated, SUM(CASE WHEN [Rows] = -1 THEN 1 ELSE 0 END) Absent,
       SUM(CASE WHEN [Rows] NOT IN (1, -1) THEN 1 ELSE 0 END) Problems FROM @log GROUP BY Tbl;
SELECT * FROM @log WHERE [Rows] <> 1 ORDER BY Tbl, Id;
IF EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1)) PRINT 'WARNING: some statements did not update exactly one row - review before committing.';
IF @DryRun = 0 AND EXISTS (SELECT 1 FROM @log WHERE [Rows] NOT IN (1, -1))
BEGIN ROLLBACK; THROW 50000, 'ROCK9086 pass 8: a guarded update did not match exactly one row; nothing committed.', 1; END

-- verify: none of the touched rows still has `= {{` directly after an assign
SELECT l.Tbl, COUNT(*) StillOld FROM @log l
WHERE (l.Tbl = 'AttributeValue' AND EXISTS (SELECT 1 FROM AttributeValue x WHERE x.Id = l.Id AND x.Value LIKE '%{[%] assign [A-Za-z]% = {{[^ ]%}} [%]}%'))
   OR (l.Tbl = 'WorkflowActionForm' AND EXISTS (SELECT 1 FROM WorkflowActionForm x WHERE x.Id = l.Id AND x.Header LIKE '%{[%] assign [A-Za-z]% = {{[^ ]%}} [%]}%'))
   OR (l.Tbl = 'HtmlContent' AND EXISTS (SELECT 1 FROM HtmlContent x WHERE x.Id = l.Id AND x.Content LIKE '%{[%] assign [A-Za-z]% = {{[^ ]%}} [%]}%'))
GROUP BY l.Tbl;

IF @DryRun = 1 BEGIN ROLLBACK; PRINT 'Dry run - rolled back.'; END ELSE BEGIN COMMIT; PRINT 'Committed. Now clear the Rock cache.'; END
""")
open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
for tbl, col, i, pairs in rows:
    for o, n, c in pairs:
        print("%-18s %10d x%d  %s  ->  %s" % (tbl, i, c, o, n))
print("rows:", len(rows))
