/* 
 * Push API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@subsplash.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace com.subsplash.Model
{
    /// <summary>
    /// Embedded properties of topic subscription.
    /// </summary>
    [DataContract]
        public partial class TopicSubscriptionEmbedded :  IEquatable<TopicSubscriptionEmbedded>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TopicSubscriptionEmbedded" /> class.
        /// </summary>
        /// <param name="platformEndpoint">platformEndpoint.</param>
        /// <param name="topic">topic.</param>
        public TopicSubscriptionEmbedded(PlatformEndpoint platformEndpoint = default(PlatformEndpoint), Topic topic = default(Topic))
        {
            this.PlatformEndpoint = platformEndpoint;
            this.Topic = topic;
        }
        
        /// <summary>
        /// Gets or Sets PlatformEndpoint
        /// </summary>
        [DataMember(Name="platform-endpoint", EmitDefaultValue=false)]
        public PlatformEndpoint PlatformEndpoint { get; set; }

        /// <summary>
        /// Gets or Sets Topic
        /// </summary>
        [DataMember(Name="topic", EmitDefaultValue=false)]
        public Topic Topic { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TopicSubscriptionEmbedded {\n");
            sb.Append("  PlatformEndpoint: ").Append(PlatformEndpoint).Append("\n");
            sb.Append("  Topic: ").Append(Topic).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TopicSubscriptionEmbedded);
        }

        /// <summary>
        /// Returns true if TopicSubscriptionEmbedded instances are equal
        /// </summary>
        /// <param name="input">Instance of TopicSubscriptionEmbedded to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TopicSubscriptionEmbedded input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PlatformEndpoint == input.PlatformEndpoint ||
                    (this.PlatformEndpoint != null &&
                    this.PlatformEndpoint.Equals(input.PlatformEndpoint))
                ) && 
                (
                    this.Topic == input.Topic ||
                    (this.Topic != null &&
                    this.Topic.Equals(input.Topic))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PlatformEndpoint != null)
                    hashCode = hashCode * 59 + this.PlatformEndpoint.GetHashCode();
                if (this.Topic != null)
                    hashCode = hashCode * 59 + this.Topic.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
