//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace org.secc.PayPalReporting.Services
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class reportingEngineRequest
    {

        private reportingEngineRequestAuthRequest authRequestField;

        private object itemField;

        /// <remarks/>
        public reportingEngineRequestAuthRequest authRequest
        {
            get
            {
                return this.authRequestField;
            }
            set
            {
                this.authRequestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("createScheduleRequest", typeof(reportingEngineRequestCreateScheduleRequest))]
        [System.Xml.Serialization.XmlElementAttribute("createTemplateRequest", typeof(reportingEngineRequestCreateTemplateRequest))]
        [System.Xml.Serialization.XmlElementAttribute("deleteScheduleRequest", typeof(reportingEngineRequestDeleteScheduleRequest))]
        [System.Xml.Serialization.XmlElementAttribute("deleteTemplateRequest", typeof(reportingEngineRequestDeleteTemplateRequest))]
        [System.Xml.Serialization.XmlElementAttribute("getDataRequest", typeof(reportingEngineRequestGetDataRequest))]
        [System.Xml.Serialization.XmlElementAttribute("getMetaDataRequest", typeof(reportingEngineRequestGetMetaDataRequest))]
        [System.Xml.Serialization.XmlElementAttribute("getResultsRequest", typeof(reportingEngineRequestGetResultsRequest))]
        [System.Xml.Serialization.XmlElementAttribute("getScheduleRequest", typeof(reportingEngineRequestGetScheduleRequest))]
        [System.Xml.Serialization.XmlElementAttribute("getTemplateRequest", typeof(reportingEngineRequestGetTemplateRequest))]
        [System.Xml.Serialization.XmlElementAttribute("runReportRequest", typeof(reportingEngineRequestRunReportRequest))]
        [System.Xml.Serialization.XmlElementAttribute("runSearchRequest", typeof(reportingEngineRequestRunSearchRequest))]
        [System.Xml.Serialization.XmlElementAttribute("updateScheduleRequest", typeof(reportingEngineRequestUpdateScheduleRequest))]
        [System.Xml.Serialization.XmlElementAttribute("updateTemplateRequest", typeof(reportingEngineRequestUpdateTemplateRequest))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestAuthRequest
    {

        private string userField;

        private string vendorField;

        private string partnerField;

        private string passwordField;

        private string executorField;

        /// <remarks/>
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        public string vendor
        {
            get
            {
                return this.vendorField;
            }
            set
            {
                this.vendorField = value;
            }
        }

        /// <remarks/>
        public string partner
        {
            get
            {
                return this.partnerField;
            }
            set
            {
                this.partnerField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string executor
        {
            get
            {
                return this.executorField;
            }
            set
            {
                this.executorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestCreateScheduleRequest
    {

        private scheduleDefinition scheduleDefinitionField;

        /// <remarks/>
        public scheduleDefinition scheduleDefinition
        {
            get
            {
                return this.scheduleDefinitionField;
            }
            set
            {
                this.scheduleDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class scheduleDefinition
    {

        private string scheduleNameField;

        private string templateNameField;

        private bool notificationRequiredField;

        private object itemField;

        private int pageSizeField;

        private bool pageSizeFieldSpecified;

        /// <remarks/>
        public string scheduleName
        {
            get
            {
                return this.scheduleNameField;
            }
            set
            {
                this.scheduleNameField = value;
            }
        }

        /// <remarks/>
        public string templateName
        {
            get
            {
                return this.templateNameField;
            }
            set
            {
                this.templateNameField = value;
            }
        }

        /// <remarks/>
        public bool notificationRequired
        {
            get
            {
                return this.notificationRequiredField;
            }
            set
            {
                this.notificationRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("daily", typeof(scheduleDefinitionDaily))]
        [System.Xml.Serialization.XmlElementAttribute("monthly", typeof(scheduleDefinitionMonthly))]
        [System.Xml.Serialization.XmlElementAttribute("weekly", typeof(scheduleDefinitionWeekly))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get
            {
                return this.pageSizeFieldSpecified;
            }
            set
            {
                this.pageSizeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class scheduleDefinitionDaily
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class scheduleDefinitionMonthly
    {

        private int dayOfMonthField;

        /// <remarks/>
        public int dayOfMonth
        {
            get
            {
                return this.dayOfMonthField;
            }
            set
            {
                this.dayOfMonthField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class scheduleDefinitionWeekly
    {

        private scheduleDefinitionWeeklyDayOfWeek dayOfWeekField;

        /// <remarks/>
        public scheduleDefinitionWeeklyDayOfWeek dayOfWeek
        {
            get
            {
                return this.dayOfWeekField;
            }
            set
            {
                this.dayOfWeekField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum scheduleDefinitionWeeklyDayOfWeek
    {

        /// <remarks/>
        Sunday,

        /// <remarks/>
        Monday,

        /// <remarks/>
        Tuesday,

        /// <remarks/>
        Wednesday,

        /// <remarks/>
        Thursday,

        /// <remarks/>
        Friday,

        /// <remarks/>
        Saturday,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestCreateTemplateRequest
    {

        private templateDefinition templateDefinitionField;

        /// <remarks/>
        public templateDefinition templateDefinition
        {
            get
            {
                return this.templateDefinitionField;
            }
            set
            {
                this.templateDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class templateDefinition
    {

        private string templateNameField;

        private string reportNameField;

        private reportParam[] reportParamField;

        /// <remarks/>
        public string templateName
        {
            get
            {
                return this.templateNameField;
            }
            set
            {
                this.templateNameField = value;
            }
        }

        /// <remarks/>
        public string reportName
        {
            get
            {
                return this.reportNameField;
            }
            set
            {
                this.reportNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportParam")]
        public reportParam[] reportParam
        {
            get
            {
                return this.reportParamField;
            }
            set
            {
                this.reportParamField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class reportParam
    {

        private string paramNameField;

        private string paramValueField;

        /// <remarks/>
        public string paramName
        {
            get
            {
                return this.paramNameField;
            }
            set
            {
                this.paramNameField = value;
            }
        }

        /// <remarks/>
        public string paramValue
        {
            get
            {
                return this.paramValueField;
            }
            set
            {
                this.paramValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestDeleteScheduleRequest
    {

        private string scheduleNameField;

        /// <remarks/>
        public string scheduleName
        {
            get
            {
                return this.scheduleNameField;
            }
            set
            {
                this.scheduleNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestDeleteTemplateRequest
    {

        private string templateNameField;

        /// <remarks/>
        public string templateName
        {
            get
            {
                return this.templateNameField;
            }
            set
            {
                this.templateNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestGetDataRequest
    {

        private string reportIdField;

        private int pageNumField;

        private bool pageNumFieldSpecified;

        /// <remarks/>
        public string reportId
        {
            get
            {
                return this.reportIdField;
            }
            set
            {
                this.reportIdField = value;
            }
        }

        /// <remarks/>
        public int pageNum
        {
            get
            {
                return this.pageNumField;
            }
            set
            {
                this.pageNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumSpecified
        {
            get
            {
                return this.pageNumFieldSpecified;
            }
            set
            {
                this.pageNumFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestGetMetaDataRequest
    {

        private string reportIdField;

        /// <remarks/>
        public string reportId
        {
            get
            {
                return this.reportIdField;
            }
            set
            {
                this.reportIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestGetResultsRequest
    {

        private string itemField;

        private ItemChoiceType3 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("reportName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("scheduleName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("searchName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("templateName", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemChoiceType3
    {

        /// <remarks/>
        reportId,

        /// <remarks/>
        reportName,

        /// <remarks/>
        scheduleName,

        /// <remarks/>
        searchName,

        /// <remarks/>
        templateName,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestGetScheduleRequest
    {

        private string itemField;

        private ItemChoiceType1 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scheduleName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("templateName", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        scheduleName,

        /// <remarks/>
        templateName,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestGetTemplateRequest
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("templateName", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        reportName,

        /// <remarks/>
        templateName,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestRunReportRequest
    {

        private string itemField;

        private reportType itemElementNameField;

        private reportParam[] reportParamField;

        private bool notificationRequiredField;

        private bool notificationRequiredFieldSpecified;

        private int pageSizeField;

        private bool pageSizeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("templateName", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public reportType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportParam")]
        public reportParam[] reportParam
        {
            get
            {
                return this.reportParamField;
            }
            set
            {
                this.reportParamField = value;
            }
        }

        /// <remarks/>
        public bool notificationRequired
        {
            get
            {
                return this.notificationRequiredField;
            }
            set
            {
                this.notificationRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notificationRequiredSpecified
        {
            get
            {
                return this.notificationRequiredFieldSpecified;
            }
            set
            {
                this.notificationRequiredFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get
            {
                return this.pageSizeFieldSpecified;
            }
            set
            {
                this.pageSizeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum reportType
    {

        /// <remarks/>
        reportName,

        /// <remarks/>
        templateName,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestRunSearchRequest
    {

        private string searchNameField;

        private reportParam[] reportParamField;

        private int pageSizeField;

        private bool pageSizeFieldSpecified;

        /// <remarks/>
        public string searchName
        {
            get
            {
                return this.searchNameField;
            }
            set
            {
                this.searchNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportParam")]
        public reportParam[] reportParam
        {
            get
            {
                return this.reportParamField;
            }
            set
            {
                this.reportParamField = value;
            }
        }

        /// <remarks/>
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get
            {
                return this.pageSizeFieldSpecified;
            }
            set
            {
                this.pageSizeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestUpdateScheduleRequest
    {

        private scheduleDefinition scheduleDefinitionField;

        /// <remarks/>
        public scheduleDefinition scheduleDefinition
        {
            get
            {
                return this.scheduleDefinitionField;
            }
            set
            {
                this.scheduleDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineRequestUpdateTemplateRequest
    {

        private templateDefinition templateDefinitionField;

        /// <remarks/>
        public templateDefinition templateDefinition
        {
            get
            {
                return this.templateDefinitionField;
            }
            set
            {
                this.templateDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class reportingEngineResponse
    {

        private reportingEngineResponseBaseResponse baseResponseField;

        private object itemField;

        /// <remarks/>
        public reportingEngineResponseBaseResponse baseResponse
        {
            get
            {
                return this.baseResponseField;
            }
            set
            {
                this.baseResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("getDataResponse", typeof(reportingEngineResponseGetDataResponse))]
        [System.Xml.Serialization.XmlElementAttribute("getMetaDataResponse", typeof(reportingEngineResponseGetMetaDataResponse))]
        [System.Xml.Serialization.XmlElementAttribute("getResultsResponse", typeof(reportingEngineResponseGetResultsResponse))]
        [System.Xml.Serialization.XmlElementAttribute("getScheduleResponse", typeof(reportingEngineResponseGetScheduleResponse))]
        [System.Xml.Serialization.XmlElementAttribute("getTemplateResponse", typeof(reportingEngineResponseGetTemplateResponse))]
        [System.Xml.Serialization.XmlElementAttribute("runReportResponse", typeof(reportingEngineResponseRunReportResponse))]
        [System.Xml.Serialization.XmlElementAttribute("runSearchResponse", typeof(reportingEngineResponseRunSearchResponse))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseBaseResponse
    {

        private int responseCodeField;

        private string responseMsgField;

        /// <remarks/>
        public int responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }

        /// <remarks/>
        public string responseMsg
        {
            get
            {
                return this.responseMsgField;
            }
            set
            {
                this.responseMsgField = value;
            }
        }
    }

  



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseGetMetaDataResponse
    {

        private int numberOfRowsField;

        private int numberOfPagesField;

        private int pageSizeField;

        private int numberOfColumnsField;

        private reportingEngineResponseGetMetaDataResponseColumnMetaData[] columnMetaDataField;

        /// <remarks/>
        public int numberOfRows
        {
            get
            {
                return this.numberOfRowsField;
            }
            set
            {
                this.numberOfRowsField = value;
            }
        }

        /// <remarks/>
        public int numberOfPages
        {
            get
            {
                return this.numberOfPagesField;
            }
            set
            {
                this.numberOfPagesField = value;
            }
        }

        /// <remarks/>
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }

        /// <remarks/>
        public int numberOfColumns
        {
            get
            {
                return this.numberOfColumnsField;
            }
            set
            {
                this.numberOfColumnsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("columnMetaData")]
        public reportingEngineResponseGetMetaDataResponseColumnMetaData[] columnMetaData
        {
            get
            {
                return this.columnMetaDataField;
            }
            set
            {
                this.columnMetaDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseGetMetaDataResponseColumnMetaData
    {

        private string dataNameField;

        private reportingEngineResponseGetMetaDataResponseColumnMetaDataDataType dataTypeField;

        /// <remarks/>
        public string dataName
        {
            get
            {
                return this.dataNameField;
            }
            set
            {
                this.dataNameField = value;
            }
        }

        /// <remarks/>
        public reportingEngineResponseGetMetaDataResponseColumnMetaDataDataType dataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum reportingEngineResponseGetMetaDataResponseColumnMetaDataDataType
    {

        /// <remarks/>
        @string,

        /// <remarks/>
        number,

        /// <remarks/>
        date,

        /// <remarks/>
        currency,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseGetResultsResponse
    {

        private reportingEngineResponseGetResultsResponseResults[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Results")]
        public reportingEngineResponseGetResultsResponseResults[] Results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseGetResultsResponseResults
    {

        private string reportIdField;

        private int statusCodeField;

        private string statusMsgField;

        private System.DateTime executionTimeField;

        private bool executionTimeFieldSpecified;

        private string scheduleNameField;

        private string reportNameField;

        private string templateNameField;

        private string searchNameField;

        /// <remarks/>
        public string reportId
        {
            get
            {
                return this.reportIdField;
            }
            set
            {
                this.reportIdField = value;
            }
        }

        /// <remarks/>
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        public string statusMsg
        {
            get
            {
                return this.statusMsgField;
            }
            set
            {
                this.statusMsgField = value;
            }
        }

        /// <remarks/>
        public System.DateTime executionTime
        {
            get
            {
                return this.executionTimeField;
            }
            set
            {
                this.executionTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool executionTimeSpecified
        {
            get
            {
                return this.executionTimeFieldSpecified;
            }
            set
            {
                this.executionTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string scheduleName
        {
            get
            {
                return this.scheduleNameField;
            }
            set
            {
                this.scheduleNameField = value;
            }
        }

        /// <remarks/>
        public string reportName
        {
            get
            {
                return this.reportNameField;
            }
            set
            {
                this.reportNameField = value;
            }
        }

        /// <remarks/>
        public string templateName
        {
            get
            {
                return this.templateNameField;
            }
            set
            {
                this.templateNameField = value;
            }
        }

        /// <remarks/>
        public string searchName
        {
            get
            {
                return this.searchNameField;
            }
            set
            {
                this.searchNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseGetScheduleResponse
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scheduleDefinition", typeof(scheduleDefinition))]
        [System.Xml.Serialization.XmlElementAttribute("scheduleName", typeof(string))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseGetTemplateResponse
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("templateDefinition", typeof(templateDefinition))]
        [System.Xml.Serialization.XmlElementAttribute("templateName", typeof(string))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseRunReportResponse
    {

        private string reportIdField;

        private int statusCodeField;

        private string statusMsgField;

        /// <remarks/>
        public string reportId
        {
            get
            {
                return this.reportIdField;
            }
            set
            {
                this.reportIdField = value;
            }
        }

        /// <remarks/>
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        public string statusMsg
        {
            get
            {
                return this.statusMsgField;
            }
            set
            {
                this.statusMsgField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseRunSearchResponse
    {

        private string reportIdField;

        private int statusCodeField;

        private string statusMsgField;

        /// <remarks/>
        public string reportId
        {
            get
            {
                return this.reportIdField;
            }
            set
            {
                this.reportIdField = value;
            }
        }

        /// <remarks/>
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        public string statusMsg
        {
            get
            {
                return this.statusMsgField;
            }
            set
            {
                this.statusMsgField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class reportDefinition
    {
    }

#region getDataResponse

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseGetDataResponse
    {

        private string reportIdField;

        private int pageNumField;

        private reportingEngineResponseGetDataResponseReportDataRow[] reportDataRowField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportId
        {
            get
            {
                return this.reportIdField;
            }
            set
            {
                this.reportIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageNum
        {
            get
            {
                return this.pageNumField;
            }
            set
            {
                this.pageNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportDataRow", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public reportingEngineResponseGetDataResponseReportDataRow[] reportDataRow
        {
            get
            {
                return this.reportDataRowField;
            }
            set
            {
                this.reportDataRowField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseGetDataResponseReportDataRow
    {

        private reportingEngineResponseGetDataResponseReportDataRowColumnData[] columnDataField;

        private string rowNumField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("columnData", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public reportingEngineResponseGetDataResponseReportDataRowColumnData[] columnData
        {
            get
            {
                return this.columnDataField;
            }
            set
            {
                this.columnDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rowNum
        {
            get
            {
                return this.rowNumField;
            }
            set
            {
                this.rowNumField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class reportingEngineResponseGetDataResponseReportDataRowColumnData
    {

        private string dataField;

        private string colNumField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string colNum
        {
            get
            {
                return this.colNumField;
            }
            set
            {
                this.colNumField = value;
            }
        }
    }
#endregion

}